/*flexberryautogenerated="true"*/
namespace IIS.Авиакомпания
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class КомпанияИзготовительL : BaseListForm<КомпанияИзготовитель>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public КомпанияИзготовительL() : base(КомпанияИзготовитель.Views.КомпанияИзготовительL)
        {
            EditPage = КомпанияИзготовительE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/KompaniyaIzgotovitel/KompaniyaIzgotovitelL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
