/*flexberryautogenerated="true"*/
namespace IIS.Ипподром
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class СпортивныйРазрядL : BaseListForm<СпортивныйРазряд>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public СпортивныйРазрядL() : base(СпортивныйРазряд.Views.СпортивныйРазрядL)
        {
            EditPage = СпортивныйРазрядE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Jockey/SportivnyjRazryadL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
