//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ippodrom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЛошадьВСостязании.
    /// </summary>
    // *** Start programmer edit section *** (ЛошадьВСостязании CustomAttributes)

    // *** End programmer edit section *** (ЛошадьВСостязании CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛошадьВСостязанииE", new string[] {
            "Место",
            "Состязание"})]
    [MasterViewDefineAttribute("ЛошадьВСостязанииE", "Состязание", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НазваниеСостязания")]
    public class ЛошадьВСостязании : ICSSoft.STORMNET.DataObject
    {
        
        private int fМесто;
        
        private IIS.Ippodrom.Состязание fСостязание;
        
        private IIS.Ippodrom.Лошадь fЛошадь;
        
        // *** Start programmer edit section *** (ЛошадьВСостязании CustomMembers)

        // *** End programmer edit section *** (ЛошадьВСостязании CustomMembers)

        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (ЛошадьВСостязании.Место CustomAttributes)

        // *** End programmer edit section *** (ЛошадьВСостязании.Место CustomAttributes)
        public virtual int Место
        {
            get
            {
                // *** Start programmer edit section *** (ЛошадьВСостязании.Место Get start)

                // *** End programmer edit section *** (ЛошадьВСостязании.Место Get start)
                int result = this.fМесто;
                // *** Start programmer edit section *** (ЛошадьВСостязании.Место Get end)

                // *** End programmer edit section *** (ЛошадьВСостязании.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛошадьВСостязании.Место Set start)

                // *** End programmer edit section *** (ЛошадьВСостязании.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (ЛошадьВСостязании.Место Set end)

                // *** End programmer edit section *** (ЛошадьВСостязании.Место Set end)
            }
        }
        
        /// <summary>
        /// ЛошадьВСостязании.
        /// </summary>
        // *** Start programmer edit section *** (ЛошадьВСостязании.Состязание CustomAttributes)

        // *** End programmer edit section *** (ЛошадьВСостязании.Состязание CustomAttributes)
        [PropertyStorage(new string[] {
                "Состязание"})]
        [NotNull()]
        public virtual IIS.Ippodrom.Состязание Состязание
        {
            get
            {
                // *** Start programmer edit section *** (ЛошадьВСостязании.Состязание Get start)

                // *** End programmer edit section *** (ЛошадьВСостязании.Состязание Get start)
                IIS.Ippodrom.Состязание result = this.fСостязание;
                // *** Start programmer edit section *** (ЛошадьВСостязании.Состязание Get end)

                // *** End programmer edit section *** (ЛошадьВСостязании.Состязание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛошадьВСостязании.Состязание Set start)

                // *** End programmer edit section *** (ЛошадьВСостязании.Состязание Set start)
                this.fСостязание = value;
                // *** Start programmer edit section *** (ЛошадьВСостязании.Состязание Set end)

                // *** End programmer edit section *** (ЛошадьВСостязании.Состязание Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Ippodrom.Лошадь.
        /// </summary>
        // *** Start programmer edit section *** (ЛошадьВСостязании.Лошадь CustomAttributes)

        // *** End programmer edit section *** (ЛошадьВСостязании.Лошадь CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Лошадь"})]
        public virtual IIS.Ippodrom.Лошадь Лошадь
        {
            get
            {
                // *** Start programmer edit section *** (ЛошадьВСостязании.Лошадь Get start)

                // *** End programmer edit section *** (ЛошадьВСостязании.Лошадь Get start)
                IIS.Ippodrom.Лошадь result = this.fЛошадь;
                // *** Start programmer edit section *** (ЛошадьВСостязании.Лошадь Get end)

                // *** End programmer edit section *** (ЛошадьВСостязании.Лошадь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛошадьВСостязании.Лошадь Set start)

                // *** End programmer edit section *** (ЛошадьВСостязании.Лошадь Set start)
                this.fЛошадь = value;
                // *** Start programmer edit section *** (ЛошадьВСостязании.Лошадь Set end)

                // *** End programmer edit section *** (ЛошадьВСостязании.Лошадь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛошадьВСостязанииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛошадьВСостязанииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛошадьВСостязанииE", typeof(IIS.Ippodrom.ЛошадьВСостязании));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЛошадьВСостязании.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЛошадьВСостязании CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЛошадьВСостязании CustomAttributes)
    public class DetailArrayOfЛошадьВСостязании : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Ippodrom.DetailArrayOfЛошадьВСостязании members)

        // *** End programmer edit section *** (IIS.Ippodrom.DetailArrayOfЛошадьВСостязании members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЛошадьВСостязании by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЛошадьВСостязании.
        /// </summary>
        public DetailArrayOfЛошадьВСостязании(IIS.Ippodrom.Лошадь fЛошадь) : 
                base(typeof(ЛошадьВСостязании), ((ICSSoft.STORMNET.DataObject)(fЛошадь)))
        {
        }
        
        public IIS.Ippodrom.ЛошадьВСостязании this[int index]
        {
            get
            {
                return ((IIS.Ippodrom.ЛошадьВСостязании)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Ippodrom.ЛошадьВСостязании dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
