//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Горводоканал
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обращение.
    /// </summary>
    // *** Start programmer edit section *** (Обращение CustomAttributes)

    // *** End programmer edit section *** (Обращение CustomAttributes)
    [BusinessServer("NewPlatform.Горводоканал.ОбращениеBS, Горводоканал(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбращениеE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "ФИООбратившегося as \'Ф и о обратившегося\' on \'-Обратившийся\'",
            "Адрес as \'Адрес\' on \'-Обратившийся\'",
            "Телефон as \'Телефон\' on \'-Обратившийся\'",
            "Тип as \'Тип\'",
            "Оператор as \'Оператор\'",
            "Ответственный as \'Ответственный\'",
            "Вид as \'Вид\'",
            "Причина as \'Причина\'"})]
    [MasterViewDefineAttribute("ОбращениеE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбращениеE", "Ответственный", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбращениеE", "Вид", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "Причина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("ОбращениеL", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "Тип.Название as \'Название\'",
            "Вид.Название as \'Название\'",
            "Причина.Название as \'Название\'"})]
    public class Обращение : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private NewPlatform.Горводоканал.tСтатусОбращения fСтатус;
        
        private System.DateTime? fДатаПоступления;
        
        private System.DateTime? fДатаЗакрытия;
        
        private string fФИООбратившегося;
        
        private string fАдрес;
        
        private string fТелефон;
        
        private NewPlatform.Горводоканал.ТипОбращения fТип;
        
        private NewPlatform.Горводоканал.Сотрудник fОператор;
        
        private NewPlatform.Горводоканал.Сотрудник fОтветственный;
        
        private NewPlatform.Горводоканал.ВидОбращения fВид;
        
        private NewPlatform.Горводоканал.ПричинаОбращения fПричина;
        
        // *** Start programmer edit section *** (Обращение CustomMembers)

        // *** End programmer edit section *** (Обращение CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Номер CustomAttributes)

        // *** End programmer edit section *** (Обращение.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Номер Get start)

                // *** End programmer edit section *** (Обращение.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Обращение.Номер Get end)

                // *** End programmer edit section *** (Обращение.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Номер Set start)

                // *** End programmer edit section *** (Обращение.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Обращение.Номер Set end)

                // *** End programmer edit section *** (Обращение.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Статус CustomAttributes)

        // *** End programmer edit section *** (Обращение.Статус CustomAttributes)
        public virtual NewPlatform.Горводоканал.tСтатусОбращения Статус
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Статус Get start)

                // *** End programmer edit section *** (Обращение.Статус Get start)
                NewPlatform.Горводоканал.tСтатусОбращения result = this.fСтатус;
                // *** Start programmer edit section *** (Обращение.Статус Get end)

                // *** End programmer edit section *** (Обращение.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Статус Set start)

                // *** End programmer edit section *** (Обращение.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Обращение.Статус Set end)

                // *** End programmer edit section *** (Обращение.Статус Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоступления.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ДатаПоступления CustomAttributes)

        // *** End programmer edit section *** (Обращение.ДатаПоступления CustomAttributes)
        public virtual System.DateTime? ДатаПоступления
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Get start)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Get start)
                System.DateTime? result = this.fДатаПоступления;
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Get end)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Set start)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Set start)
                this.fДатаПоступления = value;
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Set end)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗакрытия.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ДатаЗакрытия CustomAttributes)

        // *** End programmer edit section *** (Обращение.ДатаЗакрытия CustomAttributes)
        public virtual System.DateTime? ДатаЗакрытия
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Get start)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Get start)
                System.DateTime? result = this.fДатаЗакрытия;
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Get end)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Set start)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Set start)
                this.fДатаЗакрытия = value;
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Set end)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Set end)
            }
        }
        
        /// <summary>
        /// ФИООбратившегося.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ФИООбратившегося CustomAttributes)

        // *** End programmer edit section *** (Обращение.ФИООбратившегося CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string ФИООбратившегося
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Get start)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Get start)
                string result = this.fФИООбратившегося;
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Get end)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Set start)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Set start)
                this.fФИООбратившегося = value;
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Set end)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Адрес CustomAttributes)

        // *** End programmer edit section *** (Обращение.Адрес CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Адрес Get start)

                // *** End programmer edit section *** (Обращение.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Обращение.Адрес Get end)

                // *** End programmer edit section *** (Обращение.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Адрес Set start)

                // *** End programmer edit section *** (Обращение.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Обращение.Адрес Set end)

                // *** End programmer edit section *** (Обращение.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Телефон CustomAttributes)

        // *** End programmer edit section *** (Обращение.Телефон CustomAttributes)
        [StrLen(150)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Телефон Get start)

                // *** End programmer edit section *** (Обращение.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Обращение.Телефон Get end)

                // *** End programmer edit section *** (Обращение.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Телефон Set start)

                // *** End programmer edit section *** (Обращение.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Обращение.Телефон Set end)

                // *** End programmer edit section *** (Обращение.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Тип CustomAttributes)

        // *** End programmer edit section *** (Обращение.Тип CustomAttributes)
        [PropertyStorage(new string[] {
                "Тип"})]
        public virtual NewPlatform.Горводоканал.ТипОбращения Тип
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Тип Get start)

                // *** End programmer edit section *** (Обращение.Тип Get start)
                NewPlatform.Горводоканал.ТипОбращения result = this.fТип;
                // *** Start programmer edit section *** (Обращение.Тип Get end)

                // *** End programmer edit section *** (Обращение.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Тип Set start)

                // *** End programmer edit section *** (Обращение.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Обращение.Тип Set end)

                // *** End programmer edit section *** (Обращение.Тип Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Оператор CustomAttributes)

        // *** End programmer edit section *** (Обращение.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        [NotNull()]
        public virtual NewPlatform.Горводоканал.Сотрудник Оператор
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Оператор Get start)

                // *** End programmer edit section *** (Обращение.Оператор Get start)
                NewPlatform.Горводоканал.Сотрудник result = this.fОператор;
                // *** Start programmer edit section *** (Обращение.Оператор Get end)

                // *** End programmer edit section *** (Обращение.Оператор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Оператор Set start)

                // *** End programmer edit section *** (Обращение.Оператор Set start)
                this.fОператор = value;
                // *** Start programmer edit section *** (Обращение.Оператор Set end)

                // *** End programmer edit section *** (Обращение.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Обращение.Ответственный CustomAttributes)
        [PropertyStorage(new string[] {
                "Ответственный"})]
        public virtual NewPlatform.Горводоканал.Сотрудник Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Ответственный Get start)

                // *** End programmer edit section *** (Обращение.Ответственный Get start)
                NewPlatform.Горводоканал.Сотрудник result = this.fОтветственный;
                // *** Start programmer edit section *** (Обращение.Ответственный Get end)

                // *** End programmer edit section *** (Обращение.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Ответственный Set start)

                // *** End programmer edit section *** (Обращение.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Обращение.Ответственный Set end)

                // *** End programmer edit section *** (Обращение.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Вид CustomAttributes)

        // *** End programmer edit section *** (Обращение.Вид CustomAttributes)
        [PropertyStorage(new string[] {
                "Вид"})]
        public virtual NewPlatform.Горводоканал.ВидОбращения Вид
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Вид Get start)

                // *** End programmer edit section *** (Обращение.Вид Get start)
                NewPlatform.Горводоканал.ВидОбращения result = this.fВид;
                // *** Start programmer edit section *** (Обращение.Вид Get end)

                // *** End programmer edit section *** (Обращение.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Вид Set start)

                // *** End programmer edit section *** (Обращение.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Обращение.Вид Set end)

                // *** End programmer edit section *** (Обращение.Вид Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Причина CustomAttributes)

        // *** End programmer edit section *** (Обращение.Причина CustomAttributes)
        [PropertyStorage(new string[] {
                "Причина"})]
        public virtual NewPlatform.Горводоканал.ПричинаОбращения Причина
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Причина Get start)

                // *** End programmer edit section *** (Обращение.Причина Get start)
                NewPlatform.Горводоканал.ПричинаОбращения result = this.fПричина;
                // *** Start programmer edit section *** (Обращение.Причина Get end)

                // *** End programmer edit section *** (Обращение.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Причина Set start)

                // *** End programmer edit section *** (Обращение.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (Обращение.Причина Set end)

                // *** End programmer edit section *** (Обращение.Причина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбращениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеE", typeof(NewPlatform.Горводоканал.Обращение));
                }
            }
            
            /// <summary>
            /// "ОбращениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеL", typeof(NewPlatform.Горводоканал.Обращение));
                }
            }
        }
    }
}
