/*flexberryautogenerated="true"*/
namespace IIS.Product_40936
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class СчетаL : BaseListForm<Счета>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public СчетаL() : base(Счета.Views.СчетаL)
        {
            EditPage = СчетаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Scheta/SchetaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
