//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ипподром
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Лошадь.
    /// </summary>
    // *** Start programmer edit section *** (Лошадь CustomAttributes)

    // *** End programmer edit section *** (Лошадь CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛошадьE", new string[] {
            "Кличка as \'Кличка\'",
            "Жокей as \'Жокей\'"})]
    [AssociatedDetailViewAttribute("ЛошадьE", "Состязания", "СостязанияE", true, "", "Состязания", true, new string[] {
            ""})]
    [View("ЛошадьL", new string[] {
            "Кличка as \'Кличка\'",
            "Жокей.ФамилияУправляющегоЖокея as \'Фамилия управляющего жокея\'"})]
    public class Лошадь : ICSSoft.STORMNET.DataObject
    {
        
        private string fКличка;
        
        private IIS.Ипподром.Жокей fЖокей;
        
        private IIS.Ипподром.DetailArrayOfСостязания fСостязания;
        
        // *** Start programmer edit section *** (Лошадь CustomMembers)

        // *** End programmer edit section *** (Лошадь CustomMembers)

        
        /// <summary>
        /// Кличка.
        /// </summary>
        // *** Start programmer edit section *** (Лошадь.Кличка CustomAttributes)

        // *** End programmer edit section *** (Лошадь.Кличка CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Кличка
        {
            get
            {
                // *** Start programmer edit section *** (Лошадь.Кличка Get start)

                // *** End programmer edit section *** (Лошадь.Кличка Get start)
                string result = this.fКличка;
                // *** Start programmer edit section *** (Лошадь.Кличка Get end)

                // *** End programmer edit section *** (Лошадь.Кличка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лошадь.Кличка Set start)

                // *** End programmer edit section *** (Лошадь.Кличка Set start)
                this.fКличка = value;
                // *** Start programmer edit section *** (Лошадь.Кличка Set end)

                // *** End programmer edit section *** (Лошадь.Кличка Set end)
            }
        }
        
        /// <summary>
        /// Лошадь.
        /// </summary>
        // *** Start programmer edit section *** (Лошадь.Жокей CustomAttributes)

        // *** End programmer edit section *** (Лошадь.Жокей CustomAttributes)
        [NotNull()]
        public virtual IIS.Ипподром.Жокей Жокей
        {
            get
            {
                // *** Start programmer edit section *** (Лошадь.Жокей Get start)

                // *** End programmer edit section *** (Лошадь.Жокей Get start)
                IIS.Ипподром.Жокей result = this.fЖокей;
                // *** Start programmer edit section *** (Лошадь.Жокей Get end)

                // *** End programmer edit section *** (Лошадь.Жокей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лошадь.Жокей Set start)

                // *** End programmer edit section *** (Лошадь.Жокей Set start)
                this.fЖокей = value;
                // *** Start programmer edit section *** (Лошадь.Жокей Set end)

                // *** End programmer edit section *** (Лошадь.Жокей Set end)
            }
        }
        
        /// <summary>
        /// Лошадь.
        /// </summary>
        // *** Start programmer edit section *** (Лошадь.Состязания CustomAttributes)

        // *** End programmer edit section *** (Лошадь.Состязания CustomAttributes)
        public virtual IIS.Ипподром.DetailArrayOfСостязания Состязания
        {
            get
            {
                // *** Start programmer edit section *** (Лошадь.Состязания Get start)

                // *** End programmer edit section *** (Лошадь.Состязания Get start)
                if ((this.fСостязания == null))
                {
                    this.fСостязания = new IIS.Ипподром.DetailArrayOfСостязания(this);
                }
                IIS.Ипподром.DetailArrayOfСостязания result = this.fСостязания;
                // *** Start programmer edit section *** (Лошадь.Состязания Get end)

                // *** End programmer edit section *** (Лошадь.Состязания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лошадь.Состязания Set start)

                // *** End programmer edit section *** (Лошадь.Состязания Set start)
                this.fСостязания = value;
                // *** Start programmer edit section *** (Лошадь.Состязания Set end)

                // *** End programmer edit section *** (Лошадь.Состязания Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛошадьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛошадьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛошадьE", typeof(IIS.Ипподром.Лошадь));
                }
            }
            
            /// <summary>
            /// "ЛошадьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛошадьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛошадьL", typeof(IIS.Ипподром.Лошадь));
                }
            }
        }
    }
}
