//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ипподром
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спортивный разряд.
    /// </summary>
    // *** Start programmer edit section *** (СпортивныйРазряд CustomAttributes)

    // *** End programmer edit section *** (СпортивныйРазряд CustomAttributes)
    [AutoAltered()]
    [Caption("Спортивный разряд")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпортивныйРазрядE", new string[] {
            "РазрядЖокея as \'Разряд жокея\'"})]
    [View("СпортивныйРазрядL", new string[] {
            "РазрядЖокея as \'Разряд жокея\'"})]
    public class СпортивныйРазряд : ICSSoft.STORMNET.DataObject
    {
        
        private string fРазрядЖокея;
        
        // *** Start programmer edit section *** (СпортивныйРазряд CustomMembers)

        // *** End programmer edit section *** (СпортивныйРазряд CustomMembers)

        
        /// <summary>
        /// РазрядЖокея.
        /// </summary>
        // *** Start programmer edit section *** (СпортивныйРазряд.РазрядЖокея CustomAttributes)

        // *** End programmer edit section *** (СпортивныйРазряд.РазрядЖокея CustomAttributes)
        [StrLen(255)]
        public virtual string РазрядЖокея
        {
            get
            {
                // *** Start programmer edit section *** (СпортивныйРазряд.РазрядЖокея Get start)

                // *** End programmer edit section *** (СпортивныйРазряд.РазрядЖокея Get start)
                string result = this.fРазрядЖокея;
                // *** Start programmer edit section *** (СпортивныйРазряд.РазрядЖокея Get end)

                // *** End programmer edit section *** (СпортивныйРазряд.РазрядЖокея Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпортивныйРазряд.РазрядЖокея Set start)

                // *** End programmer edit section *** (СпортивныйРазряд.РазрядЖокея Set start)
                this.fРазрядЖокея = value;
                // *** Start programmer edit section *** (СпортивныйРазряд.РазрядЖокея Set end)

                // *** End programmer edit section *** (СпортивныйРазряд.РазрядЖокея Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпортивныйРазрядE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпортивныйРазрядE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпортивныйРазрядE", typeof(IIS.Ипподром.СпортивныйРазряд));
                }
            }
            
            /// <summary>
            /// "СпортивныйРазрядL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпортивныйРазрядL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпортивныйРазрядL", typeof(IIS.Ипподром.СпортивныйРазряд));
                }
            }
        }
    }
}
