/*flexberryautogenerated="true"*/
namespace IIS.Indiv_Bahtin
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class АвтомашинаL : BaseListForm<Автомашина>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public АвтомашинаL() : base(Автомашина.Views.АвтомашинаL)
        {
            EditPage = АвтомашинаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Avtomashina/AvtomashinaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
