//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СостояниеНакладной.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеНакладной CustomAttributes)

    // *** End programmer edit section *** (СостояниеНакладной CustomAttributes)
    public enum СостояниеНакладной
    {
        
        // *** Start programmer edit section *** (СостояниеНакладной.Новая CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Новая CustomAttributes)
        Новая,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Выписанная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Выписанная CustomAttributes)
        Выписанная,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Приостановленная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Приостановленная CustomAttributes)
        Приостановленная,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Готовая CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Готовая CustomAttributes)
        Готовая,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Отгруженная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Отгруженная CustomAttributes)
        Отгруженная,
    }
}
