//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Книги
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Автор.
    /// </summary>
    // *** Start programmer edit section *** (Автор CustomAttributes)

    // *** End programmer edit section *** (Автор CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АвторE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'"})]
    [AssociatedDetailViewAttribute("АвторE", "АвторКнига", "АвторКнигаE", true, "", "Автор книга", true, new string[] {
            ""})]
    [View("АвторL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'"})]
    public class Автор : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private IIS.Книги.DetailArrayOfАвторКнига fАвторКнига;
        
        // *** Start programmer edit section *** (Автор CustomMembers)

        // *** End programmer edit section *** (Автор CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Автор.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Автор.Фамилия CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Автор.Фамилия Get start)

                // *** End programmer edit section *** (Автор.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Автор.Фамилия Get end)

                // *** End programmer edit section *** (Автор.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автор.Фамилия Set start)

                // *** End programmer edit section *** (Автор.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Автор.Фамилия Set end)

                // *** End programmer edit section *** (Автор.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Автор.Имя CustomAttributes)

        // *** End programmer edit section *** (Автор.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Автор.Имя Get start)

                // *** End programmer edit section *** (Автор.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Автор.Имя Get end)

                // *** End programmer edit section *** (Автор.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автор.Имя Set start)

                // *** End programmer edit section *** (Автор.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Автор.Имя Set end)

                // *** End programmer edit section *** (Автор.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Автор.Отчество CustomAttributes)

        // *** End programmer edit section *** (Автор.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Автор.Отчество Get start)

                // *** End programmer edit section *** (Автор.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Автор.Отчество Get end)

                // *** End programmer edit section *** (Автор.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автор.Отчество Set start)

                // *** End programmer edit section *** (Автор.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Автор.Отчество Set end)

                // *** End programmer edit section *** (Автор.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Автор.
        /// </summary>
        // *** Start programmer edit section *** (Автор.АвторКнига CustomAttributes)

        // *** End programmer edit section *** (Автор.АвторКнига CustomAttributes)
        public virtual IIS.Книги.DetailArrayOfАвторКнига АвторКнига
        {
            get
            {
                // *** Start programmer edit section *** (Автор.АвторКнига Get start)

                // *** End programmer edit section *** (Автор.АвторКнига Get start)
                if ((this.fАвторКнига == null))
                {
                    this.fАвторКнига = new IIS.Книги.DetailArrayOfАвторКнига(this);
                }
                IIS.Книги.DetailArrayOfАвторКнига result = this.fАвторКнига;
                // *** Start programmer edit section *** (Автор.АвторКнига Get end)

                // *** End programmer edit section *** (Автор.АвторКнига Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автор.АвторКнига Set start)

                // *** End programmer edit section *** (Автор.АвторКнига Set start)
                this.fАвторКнига = value;
                // *** Start programmer edit section *** (Автор.АвторКнига Set end)

                // *** End programmer edit section *** (Автор.АвторКнига Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АвторE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвторE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвторE", typeof(IIS.Книги.Автор));
                }
            }
            
            /// <summary>
            /// "АвторL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвторL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвторL", typeof(IIS.Книги.Автор));
                }
            }
        }
    }
}
