//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Книги
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Автор книга.
    /// </summary>
    // *** Start programmer edit section *** (АвторКнига CustomAttributes)

    // *** End programmer edit section *** (АвторКнига CustomAttributes)
    [AutoAltered()]
    [Caption("Автор книга")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АвторКнигаE", new string[] {
            "Книга as \'Книга\'",
            "Книга.Название as \'Название\'"}, Hidden=new string[] {
            "Книга.Название"})]
    [MasterViewDefineAttribute("АвторКнигаE", "Книга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class АвторКнига : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Книги.Книга fКнига;
        
        private IIS.Книги.Автор fАвтор;
        
        // *** Start programmer edit section *** (АвторКнига CustomMembers)

        // *** End programmer edit section *** (АвторКнига CustomMembers)

        
        /// <summary>
        /// Автор книга.
        /// </summary>
        // *** Start programmer edit section *** (АвторКнига.Книга CustomAttributes)

        // *** End programmer edit section *** (АвторКнига.Книга CustomAttributes)
        [PropertyStorage(new string[] {
                "Книга"})]
        [NotNull()]
        public virtual IIS.Книги.Книга Книга
        {
            get
            {
                // *** Start programmer edit section *** (АвторКнига.Книга Get start)

                // *** End programmer edit section *** (АвторКнига.Книга Get start)
                IIS.Книги.Книга result = this.fКнига;
                // *** Start programmer edit section *** (АвторКнига.Книга Get end)

                // *** End programmer edit section *** (АвторКнига.Книга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвторКнига.Книга Set start)

                // *** End programmer edit section *** (АвторКнига.Книга Set start)
                this.fКнига = value;
                // *** Start programmer edit section *** (АвторКнига.Книга Set end)

                // *** End programmer edit section *** (АвторКнига.Книга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Книги.Автор.
        /// </summary>
        // *** Start programmer edit section *** (АвторКнига.Автор CustomAttributes)

        // *** End programmer edit section *** (АвторКнига.Автор CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Автор"})]
        public virtual IIS.Книги.Автор Автор
        {
            get
            {
                // *** Start programmer edit section *** (АвторКнига.Автор Get start)

                // *** End programmer edit section *** (АвторКнига.Автор Get start)
                IIS.Книги.Автор result = this.fАвтор;
                // *** Start programmer edit section *** (АвторКнига.Автор Get end)

                // *** End programmer edit section *** (АвторКнига.Автор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвторКнига.Автор Set start)

                // *** End programmer edit section *** (АвторКнига.Автор Set start)
                this.fАвтор = value;
                // *** Start programmer edit section *** (АвторКнига.Автор Set end)

                // *** End programmer edit section *** (АвторКнига.Автор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АвторКнигаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвторКнигаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвторКнигаE", typeof(IIS.Книги.АвторКнига));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of АвторКнига.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfАвторКнига CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfАвторКнига CustomAttributes)
    public class DetailArrayOfАвторКнига : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Книги.DetailArrayOfАвторКнига members)

        // *** End programmer edit section *** (IIS.Книги.DetailArrayOfАвторКнига members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type АвторКнига by index.
        /// </summary>
        /// <summary>
        /// Adds object with type АвторКнига.
        /// </summary>
        public DetailArrayOfАвторКнига(IIS.Книги.Автор fАвтор) : 
                base(typeof(АвторКнига), ((ICSSoft.STORMNET.DataObject)(fАвтор)))
        {
        }
        
        public IIS.Книги.АвторКнига this[int index]
        {
            get
            {
                return ((IIS.Книги.АвторКнига)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Книги.АвторКнига dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
