//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Книги
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Издательство.
    /// </summary>
    // *** Start programmer edit section *** (Издательство CustomAttributes)

    // *** End programmer edit section *** (Издательство CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИздательствоE", new string[] {
            "Название as \'Название\'"})]
    [View("ИздательствоL", new string[] {
            "Название as \'Название\'"})]
    public class Издательство : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Издательство CustomMembers)

        // *** End programmer edit section *** (Издательство CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Издательство.Название CustomAttributes)

        // *** End programmer edit section *** (Издательство.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Издательство.Название Get start)

                // *** End programmer edit section *** (Издательство.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Издательство.Название Get end)

                // *** End programmer edit section *** (Издательство.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Издательство.Название Set start)

                // *** End programmer edit section *** (Издательство.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Издательство.Название Set end)

                // *** End programmer edit section *** (Издательство.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИздательствоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИздательствоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИздательствоE", typeof(IIS.Книги.Издательство));
                }
            }
            
            /// <summary>
            /// "ИздательствоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИздательствоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИздательствоL", typeof(IIS.Книги.Издательство));
                }
            }
        }
    }
}
