/*flexberryautogenerated="false"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.Collections.Generic;
using ICSSoft.STORMNET;
using DocumentFormat.OpenXml.Office2010.ExcelAc;

namespace IIS.Склад
{
    public partial class Запрос2 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var склады = ds.Query<Склад>(Склад.Views.СкладL).ToList();
            var всеТоварыНаСкладах = ds.Query<ТоварНаСкладе>(ТоварНаСкладе.Views.ТоварНаСкладеE).ToList();
            var результат = new List<ТоварНаСкладе>();
            foreach (var склад in склады)
            {
                var товарыНаСкладе = всеТоварыНаСкладах.Where(x => x.Склад.__PrimaryKey.Equals(склад.__PrimaryKey)).ToList();
                var максКоличество = товарыНаСкладе.Select(x => x.Количество).Max();

                var максКоличествоТоваров = товарыНаСкладе.Where(x => x.Количество == максКоличество).ToList();
                while (максКоличествоТоваров.Count >= 1)
                {
                    результат.Add(максКоличествоТоваров.FirstOrDefault());
                    максКоличествоТоваров.Remove(максКоличествоТоваров.FirstOrDefault());
                }
            }
            dataList.DataSource = результат;
            dataList.DataBind();
        }
    }
}
