/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.Collections.Generic;

namespace IIS.Склад
{
    public partial class Запрос5 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var склады = ds.Query<Склад>(Склад.Views.СкладL).ToList();
            var машины = ds.Query<Машина>(Машина.Views.МашинаL).ToList();
            var всеТоварыНаСкладах = ds.Query<ТоварНаСкладе>(ТоварНаСкладе.Views.ТоварНаСкладеE).ToList();
            var всеВладельцы = new List<Машина>();

            foreach (var склад in склады)
            {
                var владельцы = машины.Where(x => x.ВладелецМашины.__PrimaryKey.Equals(склад.ВладелецСклада.__PrimaryKey)).ToList();
                всеВладельцы.Add(владельцы.FirstOrDefault());
            }
            dataList.DataSource = всеВладельцы;
            dataList.DataBind();


        }
    }
}
