<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Zapros4.aspx.cs" Inherits="IIS.Склад.Запрос4" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<h1>Запрос 4</h1>
    <asp:Label Text="Получить для каждого склада количество хранящегося товара (общее и отдельно по товарам)." runat="server"></asp:Label>
    <asp:DataList ID="dataList" runat="server" BackColor="Gray" BorderColor="#666666"
            BorderStyle="outset" BorderWidth="2px" CellPadding="3" CellSpacing="2"
            Font-Names="Verdana" Font-Size="Small" GridLines="Both" RepeatDirection="Vertical" RepeatLayout="Table" >
        <HeaderTemplate>
            <b>Склад</b>
            <b>Товар</b>
            <b>Количество</b>
        </HeaderTemplate>
        <ItemStyle BorderStyle="outset" BackColor="White" ForeColor="Black" BorderWidth="2px" />
        <ItemTemplate>
            <table>
                <tr>
                    <td><asp:Label Text='<%# Eval("Склад.Название")%>' runat="server" /></td>
                    <td><asp:Label Text='<%# Eval("Товар.Наименование")%>' runat="server" /></td>
                    <td><asp:Label Text='<%# Eval("Количество")%>' runat="server" /></td>
                    </tr>
                </table>
        </ItemTemplate>

        <FooterTemplate>
        </FooterTemplate>

    </asp:DataList>
    <asp:Label Text="Общее количество." runat="server"></asp:Label>
    <asp:DataList ID="dataList1" runat="server" BackColor="Gray" BorderColor="#666666"
            BorderStyle="outset" BorderWidth="2px" CellPadding="3" CellSpacing="2"
            Font-Names="Verdana" Font-Size="Small" GridLines="Both" RepeatDirection="Vertical" RepeatLayout="Table" >
        <HeaderTemplate>
            <b>Склад</b>
            <b>Общее количество</b>
        </HeaderTemplate>
        <ItemStyle BorderStyle="outset" BackColor="White" ForeColor="Black" BorderWidth="2px" />
        <ItemTemplate>
            <table>
                <tr>
                    <td><asp:Label Text='<%# Eval("IIS.Склад.Cat.Age")%>' runat="server" /></td>
                    <td><asp:Label Text='<%# Eval("Name")%>' runat="server" /></td>
                    </tr>
                </table>
        </ItemTemplate>

        <FooterTemplate>
        </FooterTemplate>

    </asp:DataList>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
