/*flexberryautogenerated="false"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.ComponentModel;
using System.Collections.Generic;
using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
using ICSSoft.STORMNET.FunctionalLanguage;
using ICSSoft.STORMNET;
using ICSSoft.STORMNET.Windows.Forms;

namespace IIS.Склад
{
    public partial class Запрос1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            btnFind.Click += new EventHandler(this.btnFindOnClick);

        }

        void btnFindOnClick(Object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var cars = ds.Query<Машина>(Машина.Views.МашинаE.Name);

            var поставкиPseudoDetail = new PseudoDetail<Машина, Поставки>(
                Поставки.Views.ПоставкиE,
                Information.ExtractPropertyPath<Поставки>(p => p.Машина)
            );

            var машиныВПоставкахНаСклад =
                ds.Query<Машина>(Машина.Views.МашинаE)
                    .Where(c => поставкиPseudoDetail.Any(p => p.Склад.Название == sklad.Text)).ToList();

            var владельцыМашин = машиныВПоставкахНаСклад.Select(c => c.ВладелецМашины).ToList();

            ExternalLangDef ldef = ExternalLangDef.LanguageDef;

            dataList.DataSource = владельцыМашин;
            dataList.DataBind();
        }
    }
}
