<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Zapros3.aspx.cs" Inherits="IIS.Склад.Запрос3" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Запрос 3</h1>
    <asp:Label Text="Перечислить товары, которые хранятся более, чем на одном складе." runat="server"></asp:Label>
    <asp:DataList ID="dataList" runat="server" BackColor="Gray" BorderColor="#666666"
        BorderStyle="outset" BorderWidth="2px" CellPadding="3" CellSpacing="2"
        Font-Names="Verdana" Font-Size="Small" GridLines="Both" RepeatDirection="Vertical" RepeatLayout="Table">
        <HeaderTemplate>
            <b>Товар</b>
        </HeaderTemplate>
        <ItemStyle BorderStyle="outset" BackColor="White" ForeColor="Black" BorderWidth="2px" />
        <ItemTemplate>
            <asp:Label Text='<%# Eval("Товар.Наименование")%>' runat="server" />
        </ItemTemplate>

        <FooterTemplate>
        </FooterTemplate>

    </asp:DataList>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
