//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Авиакомпания
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Информация о самолете.
    /// </summary>
    // *** Start programmer edit section *** (ИнформацияОСамолете CustomAttributes)

    // *** End programmer edit section *** (ИнформацияОСамолете CustomAttributes)
    [AutoAltered()]
    [Caption("Информация о самолете")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("company", new string[] {
            "НомерСамолета as \'Номер\'",
            "ТипСамолета.Название as \'Компания\'"})]
    [View("Vozrast", new string[] {
            "ТипСамолета.Название",
            "ТипСамолета.Код",
            "Возраст"})]
    [View("ИнформацияОСамолетеE", new string[] {
            "НомерСамолета as \'Номер самолета\'",
            "Возраст as \'Возраст\'",
            "ТипСамолета as \'Тип самолета\' on \'-Тип\'",
            "ТипСамолета.Код as \'Код\' on \'-Тип\'",
            "ТипСамолета.КоличествоДвигателей as \'Количество двигателей\' on \'-Характеристики\'",
            "ТипСамолета.КоличествоМест as \'Количество мест\' on \'-Характеристики\'",
            "ТипСамолета.Масса as \'Масса\' on \'-Характеристики\'"})]
    [MasterViewDefineAttribute("ИнформацияОСамолетеE", "ТипСамолета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("ИнформацияОСамолетеL", new string[] {
            "НомерСамолета as \'Номер самолета\'",
            "ТипСамолета.Название as \'Название Самолета\'",
            "ТипСамолета.Код as \'Код\'"})]
    public class ИнформацияОСамолете : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерСамолета;
        
        private System.DateTime fВозраст;
        
        private IIS.Авиакомпания.ТипСамолета fТипСамолета;
        
        // *** Start programmer edit section *** (ИнформацияОСамолете CustomMembers)

        // *** End programmer edit section *** (ИнформацияОСамолете CustomMembers)

        
        /// <summary>
        /// НомерСамолета.
        /// </summary>
        // *** Start programmer edit section *** (ИнформацияОСамолете.НомерСамолета CustomAttributes)

        // *** End programmer edit section *** (ИнформацияОСамолете.НомерСамолета CustomAttributes)
        public virtual int НомерСамолета
        {
            get
            {
                // *** Start programmer edit section *** (ИнформацияОСамолете.НомерСамолета Get start)

                // *** End programmer edit section *** (ИнформацияОСамолете.НомерСамолета Get start)
                int result = this.fНомерСамолета;
                // *** Start programmer edit section *** (ИнформацияОСамолете.НомерСамолета Get end)

                // *** End programmer edit section *** (ИнформацияОСамолете.НомерСамолета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнформацияОСамолете.НомерСамолета Set start)

                // *** End programmer edit section *** (ИнформацияОСамолете.НомерСамолета Set start)
                this.fНомерСамолета = value;
                // *** Start programmer edit section *** (ИнформацияОСамолете.НомерСамолета Set end)

                // *** End programmer edit section *** (ИнформацияОСамолете.НомерСамолета Set end)
            }
        }
        
        /// <summary>
        /// Возраст.
        /// </summary>
        // *** Start programmer edit section *** (ИнформацияОСамолете.Возраст CustomAttributes)

        // *** End programmer edit section *** (ИнформацияОСамолете.Возраст CustomAttributes)
        public virtual System.DateTime Возраст
        {
            get
            {
                // *** Start programmer edit section *** (ИнформацияОСамолете.Возраст Get start)

                // *** End programmer edit section *** (ИнформацияОСамолете.Возраст Get start)
                System.DateTime result = this.fВозраст;
                // *** Start programmer edit section *** (ИнформацияОСамолете.Возраст Get end)

                // *** End programmer edit section *** (ИнформацияОСамолете.Возраст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнформацияОСамолете.Возраст Set start)

                // *** End programmer edit section *** (ИнформацияОСамолете.Возраст Set start)
                this.fВозраст = value;
                // *** Start programmer edit section *** (ИнформацияОСамолете.Возраст Set end)

                // *** End programmer edit section *** (ИнформацияОСамолете.Возраст Set end)
            }
        }
        
        /// <summary>
        /// Информация о самолете.
        /// </summary>
        // *** Start programmer edit section *** (ИнформацияОСамолете.ТипСамолета CustomAttributes)

        // *** End programmer edit section *** (ИнформацияОСамолете.ТипСамолета CustomAttributes)
        [PropertyStorage(new string[] {
                "ТипСамолета"})]
        [NotNull()]
        public virtual IIS.Авиакомпания.ТипСамолета ТипСамолета
        {
            get
            {
                // *** Start programmer edit section *** (ИнформацияОСамолете.ТипСамолета Get start)

                // *** End programmer edit section *** (ИнформацияОСамолете.ТипСамолета Get start)
                IIS.Авиакомпания.ТипСамолета result = this.fТипСамолета;
                // *** Start programmer edit section *** (ИнформацияОСамолете.ТипСамолета Get end)

                // *** End programmer edit section *** (ИнформацияОСамолете.ТипСамолета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнформацияОСамолете.ТипСамолета Set start)

                // *** End programmer edit section *** (ИнформацияОСамолете.ТипСамолета Set start)
                this.fТипСамолета = value;
                // *** Start programmer edit section *** (ИнформацияОСамолете.ТипСамолета Set end)

                // *** End programmer edit section *** (ИнформацияОСамолете.ТипСамолета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "company" view.
            /// </summary>
            public static ICSSoft.STORMNET.View company
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("company", typeof(IIS.Авиакомпания.ИнформацияОСамолете));
                }
            }
            
            /// <summary>
            /// "Vozrast" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Vozrast
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Vozrast", typeof(IIS.Авиакомпания.ИнформацияОСамолете));
                }
            }
            
            /// <summary>
            /// "ИнформацияОСамолетеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнформацияОСамолетеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнформацияОСамолетеE", typeof(IIS.Авиакомпания.ИнформацияОСамолете));
                }
            }
            
            /// <summary>
            /// "ИнформацияОСамолетеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнформацияОСамолетеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнформацияОСамолетеL", typeof(IIS.Авиакомпания.ИнформацияОСамолете));
                }
            }
        }
    }
}
