//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Авиакомпания
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// История ремонтов.
    /// </summary>
    // *** Start programmer edit section *** (ИсторияРемонтов CustomAttributes)

    // *** End programmer edit section *** (ИсторияРемонтов CustomAttributes)
    [AutoAltered()]
    [Caption("История ремонтов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИсторияРемонтовE", new string[] {
            "ДатаРемонта as \'Дата ремонта\'",
            "ПричинаРемонта as \'Причина ремонта\'"})]
    [View("ИсторияРемонтовL", new string[] {
            "ДатаРемонта as \'Дата ремонта\'",
            "ПричинаРемонта as \'Причина ремонта\'"})]
    public class ИсторияРемонтов : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаРемонта;
        
        private IIS.Авиакомпания.ВидОтказа fПричинаРемонта;
        
        // *** Start programmer edit section *** (ИсторияРемонтов CustomMembers)

        // *** End programmer edit section *** (ИсторияРемонтов CustomMembers)

        
        /// <summary>
        /// ДатаРемонта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРемонтов.ДатаРемонта CustomAttributes)

        // *** End programmer edit section *** (ИсторияРемонтов.ДатаРемонта CustomAttributes)
        public virtual System.DateTime ДатаРемонта
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРемонтов.ДатаРемонта Get start)

                // *** End programmer edit section *** (ИсторияРемонтов.ДатаРемонта Get start)
                System.DateTime result = this.fДатаРемонта;
                // *** Start programmer edit section *** (ИсторияРемонтов.ДатаРемонта Get end)

                // *** End programmer edit section *** (ИсторияРемонтов.ДатаРемонта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРемонтов.ДатаРемонта Set start)

                // *** End programmer edit section *** (ИсторияРемонтов.ДатаРемонта Set start)
                this.fДатаРемонта = value;
                // *** Start programmer edit section *** (ИсторияРемонтов.ДатаРемонта Set end)

                // *** End programmer edit section *** (ИсторияРемонтов.ДатаРемонта Set end)
            }
        }
        
        /// <summary>
        /// ПричинаРемонта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРемонтов.ПричинаРемонта CustomAttributes)

        // *** End programmer edit section *** (ИсторияРемонтов.ПричинаРемонта CustomAttributes)
        public virtual IIS.Авиакомпания.ВидОтказа ПричинаРемонта
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Get start)

                // *** End programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Get start)
                IIS.Авиакомпания.ВидОтказа result = this.fПричинаРемонта;
                // *** Start programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Get end)

                // *** End programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Set start)

                // *** End programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Set start)
                this.fПричинаРемонта = value;
                // *** Start programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Set end)

                // *** End programmer edit section *** (ИсторияРемонтов.ПричинаРемонта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИсторияРемонтовE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИсторияРемонтовE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИсторияРемонтовE", typeof(IIS.Авиакомпания.ИсторияРемонтов));
                }
            }
            
            /// <summary>
            /// "ИсторияРемонтовL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИсторияРемонтовL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИсторияРемонтовL", typeof(IIS.Авиакомпания.ИсторияРемонтов));
                }
            }
        }
    }
}
