//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Авиакомпания
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Компания изготовитель.
    /// </summary>
    // *** Start programmer edit section *** (КомпанияИзготовитель CustomAttributes)

    // *** End programmer edit section *** (КомпанияИзготовитель CustomAttributes)
    [AutoAltered()]
    [Caption("Компания изготовитель")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КомпанияИзготовительE", new string[] {
            "НазваниеКомпании as \'Название компании\'"})]
    [View("КомпанияИзготовительL", new string[] {
            "НазваниеКомпании as \'Название компании\'"})]
    public class КомпанияИзготовитель : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеКомпании;
        
        // *** Start programmer edit section *** (КомпанияИзготовитель CustomMembers)

        // *** End programmer edit section *** (КомпанияИзготовитель CustomMembers)

        
        /// <summary>
        /// НазваниеКомпании.
        /// </summary>
        // *** Start programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании CustomAttributes)

        // *** End programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеКомпании
        {
            get
            {
                // *** Start programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Get start)

                // *** End programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Get start)
                string result = this.fНазваниеКомпании;
                // *** Start programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Get end)

                // *** End programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Set start)

                // *** End programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Set start)
                this.fНазваниеКомпании = value;
                // *** Start programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Set end)

                // *** End programmer edit section *** (КомпанияИзготовитель.НазваниеКомпании Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КомпанияИзготовительE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомпанияИзготовительE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомпанияИзготовительE", typeof(IIS.Авиакомпания.КомпанияИзготовитель));
                }
            }
            
            /// <summary>
            /// "КомпанияИзготовительL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомпанияИзготовительL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомпанияИзготовительL", typeof(IIS.Авиакомпания.КомпанияИзготовитель));
                }
            }
        }
    }
}
