//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Авиакомпания
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники в самолете.
    /// </summary>
    // *** Start programmer edit section *** (СотрудникиВСамолете CustomAttributes)

    // *** End programmer edit section *** (СотрудникиВСамолете CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудники в самолете")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиВСамолетеE", new string[] {
            "ИнформацияОСамолете as \'Номер Самолета\'",
            "Сотрудники as \'Сотрудник\'",
            "Сотрудники.Должность as \'Должность\'",
            "ДатаВылета"})]
    [MasterViewDefineAttribute("СотрудникиВСамолетеE", "ИнформацияОСамолете", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерСамолета")]
    [MasterViewDefineAttribute("СотрудникиВСамолетеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("СотрудникиВСамолетеL", new string[] {
            "ИнформацияОСамолете.НомерСамолета as \'Номер самолета\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'",
            "ДатаВылета"})]
    public class СотрудникиВСамолете : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВылета;
        
        private IIS.Авиакомпания.ИнформацияОСамолете fИнформацияОСамолете;
        
        private IIS.Авиакомпания.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (СотрудникиВСамолете CustomMembers)

        // *** End programmer edit section *** (СотрудникиВСамолете CustomMembers)

        
        /// <summary>
        /// ДатаВылета.
        /// </summary>
        // *** Start programmer edit section *** (СотрудникиВСамолете.ДатаВылета CustomAttributes)

        // *** End programmer edit section *** (СотрудникиВСамолете.ДатаВылета CustomAttributes)
        public virtual System.DateTime ДатаВылета
        {
            get
            {
                // *** Start programmer edit section *** (СотрудникиВСамолете.ДатаВылета Get start)

                // *** End programmer edit section *** (СотрудникиВСамолете.ДатаВылета Get start)
                System.DateTime result = this.fДатаВылета;
                // *** Start programmer edit section *** (СотрудникиВСамолете.ДатаВылета Get end)

                // *** End programmer edit section *** (СотрудникиВСамолете.ДатаВылета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СотрудникиВСамолете.ДатаВылета Set start)

                // *** End programmer edit section *** (СотрудникиВСамолете.ДатаВылета Set start)
                this.fДатаВылета = value;
                // *** Start programmer edit section *** (СотрудникиВСамолете.ДатаВылета Set end)

                // *** End programmer edit section *** (СотрудникиВСамолете.ДатаВылета Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники в самолете.
        /// </summary>
        // *** Start programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете CustomAttributes)

        // *** End programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете CustomAttributes)
        [PropertyStorage(new string[] {
                "ИнформацияОСамолете"})]
        [NotNull()]
        public virtual IIS.Авиакомпания.ИнформацияОСамолете ИнформацияОСамолете
        {
            get
            {
                // *** Start programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Get start)

                // *** End programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Get start)
                IIS.Авиакомпания.ИнформацияОСамолете result = this.fИнформацияОСамолете;
                // *** Start programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Get end)

                // *** End programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Set start)

                // *** End programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Set start)
                this.fИнформацияОСамолете = value;
                // *** Start programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Set end)

                // *** End programmer edit section *** (СотрудникиВСамолете.ИнформацияОСамолете Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники в самолете.
        /// </summary>
        // *** Start programmer edit section *** (СотрудникиВСамолете.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (СотрудникиВСамолете.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Авиакомпания.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (СотрудникиВСамолете.Сотрудники Get start)

                // *** End programmer edit section *** (СотрудникиВСамолете.Сотрудники Get start)
                IIS.Авиакомпания.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (СотрудникиВСамолете.Сотрудники Get end)

                // *** End programmer edit section *** (СотрудникиВСамолете.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СотрудникиВСамолете.Сотрудники Set start)

                // *** End programmer edit section *** (СотрудникиВСамолете.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (СотрудникиВСамолете.Сотрудники Set end)

                // *** End programmer edit section *** (СотрудникиВСамолете.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиВСамолетеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиВСамолетеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиВСамолетеE", typeof(IIS.Авиакомпания.СотрудникиВСамолете));
                }
            }
            
            /// <summary>
            /// "СотрудникиВСамолетеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиВСамолетеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиВСамолетеL", typeof(IIS.Авиакомпания.СотрудникиВСамолете));
                }
            }
        }
    }
}
