//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Накладная.
    /// </summary>
    // *** Start programmer edit section *** (Накладная CustomAttributes)

    // *** End programmer edit section *** (Накладная CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НакладнаяE", new string[] {
            "Статус as \'Статус\'",
            "ДатаВремяОтгрузки as \'Дата время отгрузки\'",
            "Сумма as \'Сумма\'",
            "Вес as \'Вес\'",
            "Примечание as \'Примечание\'",
            "ФИОПолучателя as \'Ф и о получателя\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "Заказ as \'Заказ\'",
            "Заказ.Статус as \'Статус\'",
            "Бухгалтер as \'Бухгалтер\'",
            "Бухгалтер.Фамилия as \'Фамилия\'"})]
    [AssociatedDetailViewAttribute("НакладнаяE", "ЗаписьВНакладной", "ЗаписьВНакладнойE", true, "", "Запись в накладной", true, new string[] {
            ""})]
    [View("НакладнаяL", new string[] {
            "Статус as \'Статус\'",
            "ДатаВремяОтгрузки as \'Дата время отгрузки\'",
            "Сумма as \'Сумма\'",
            "Вес as \'Вес\'",
            "Примечание as \'Примечание\'",
            "ФИОПолучателя as \'Ф и о получателя\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "Заказ.Статус as \'Статус\'",
            "Бухгалтер.Фамилия as \'Фамилия\'"})]
    public class Накладная : IIS.Склад.Документ
    {
        
        private IIS.Склад.состояниеНакладной fСтатус;
        
        private System.DateTime fДатаВремяОтгрузки;
        
        private double fСумма;
        
        private double fВес;
        
        private string fПримечание;
        
        private string fФИОПолучателя;
        
        private IIS.Склад.Заказ fЗаказ;
        
        private IIS.Склад.Сотрудник fБухгалтер;
        
        private IIS.Склад.DetailArrayOfЗаписьВНакладной fЗаписьВНакладной;
        
        // *** Start programmer edit section *** (Накладная CustomMembers)

        // *** End programmer edit section *** (Накладная CustomMembers)

        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Статус CustomAttributes)

        // *** End programmer edit section *** (Накладная.Статус CustomAttributes)
        public virtual IIS.Склад.состояниеНакладной Статус
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Статус Get start)

                // *** End programmer edit section *** (Накладная.Статус Get start)
                IIS.Склад.состояниеНакладной result = this.fСтатус;
                // *** Start programmer edit section *** (Накладная.Статус Get end)

                // *** End programmer edit section *** (Накладная.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Статус Set start)

                // *** End programmer edit section *** (Накладная.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Накладная.Статус Set end)

                // *** End programmer edit section *** (Накладная.Статус Set end)
            }
        }
        
        /// <summary>
        /// ДатаВремяОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ДатаВремяОтгрузки CustomAttributes)

        // *** End programmer edit section *** (Накладная.ДатаВремяОтгрузки CustomAttributes)
        public virtual System.DateTime ДатаВремяОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ДатаВремяОтгрузки Get start)

                // *** End programmer edit section *** (Накладная.ДатаВремяОтгрузки Get start)
                System.DateTime result = this.fДатаВремяОтгрузки;
                // *** Start programmer edit section *** (Накладная.ДатаВремяОтгрузки Get end)

                // *** End programmer edit section *** (Накладная.ДатаВремяОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ДатаВремяОтгрузки Set start)

                // *** End programmer edit section *** (Накладная.ДатаВремяОтгрузки Set start)
                this.fДатаВремяОтгрузки = value;
                // *** Start programmer edit section *** (Накладная.ДатаВремяОтгрузки Set end)

                // *** End programmer edit section *** (Накладная.ДатаВремяОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Сумма CustomAttributes)

        // *** End programmer edit section *** (Накладная.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Сумма Get start)

                // *** End programmer edit section *** (Накладная.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Накладная.Сумма Get end)

                // *** End programmer edit section *** (Накладная.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Сумма Set start)

                // *** End programmer edit section *** (Накладная.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Накладная.Сумма Set end)

                // *** End programmer edit section *** (Накладная.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Вес.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Вес CustomAttributes)

        // *** End programmer edit section *** (Накладная.Вес CustomAttributes)
        public virtual double Вес
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Вес Get start)

                // *** End programmer edit section *** (Накладная.Вес Get start)
                double result = this.fВес;
                // *** Start programmer edit section *** (Накладная.Вес Get end)

                // *** End programmer edit section *** (Накладная.Вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Вес Set start)

                // *** End programmer edit section *** (Накладная.Вес Set start)
                this.fВес = value;
                // *** Start programmer edit section *** (Накладная.Вес Set end)

                // *** End programmer edit section *** (Накладная.Вес Set end)
            }
        }
        
        /// <summary>
        /// Примечание.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Примечание CustomAttributes)

        // *** End programmer edit section *** (Накладная.Примечание CustomAttributes)
        [StrLen(255)]
        public virtual string Примечание
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Примечание Get start)

                // *** End programmer edit section *** (Накладная.Примечание Get start)
                string result = this.fПримечание;
                // *** Start programmer edit section *** (Накладная.Примечание Get end)

                // *** End programmer edit section *** (Накладная.Примечание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Примечание Set start)

                // *** End programmer edit section *** (Накладная.Примечание Set start)
                this.fПримечание = value;
                // *** Start programmer edit section *** (Накладная.Примечание Set end)

                // *** End programmer edit section *** (Накладная.Примечание Set end)
            }
        }
        
        /// <summary>
        /// ФИОПолучателя.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ФИОПолучателя CustomAttributes)

        // *** End programmer edit section *** (Накладная.ФИОПолучателя CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОПолучателя
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Get start)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Get start)
                string result = this.fФИОПолучателя;
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Get end)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Set start)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Set start)
                this.fФИОПолучателя = value;
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Set end)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Заказ CustomAttributes)

        // *** End programmer edit section *** (Накладная.Заказ CustomAttributes)
        [NotNull()]
        public virtual IIS.Склад.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Заказ Get start)

                // *** End programmer edit section *** (Накладная.Заказ Get start)
                IIS.Склад.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Накладная.Заказ Get end)

                // *** End programmer edit section *** (Накладная.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Заказ Set start)

                // *** End programmer edit section *** (Накладная.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Накладная.Заказ Set end)

                // *** End programmer edit section *** (Накладная.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Бухгалтер CustomAttributes)

        // *** End programmer edit section *** (Накладная.Бухгалтер CustomAttributes)
        [NotNull()]
        public virtual IIS.Склад.Сотрудник Бухгалтер
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Бухгалтер Get start)

                // *** End programmer edit section *** (Накладная.Бухгалтер Get start)
                IIS.Склад.Сотрудник result = this.fБухгалтер;
                // *** Start programmer edit section *** (Накладная.Бухгалтер Get end)

                // *** End programmer edit section *** (Накладная.Бухгалтер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Бухгалтер Set start)

                // *** End programmer edit section *** (Накладная.Бухгалтер Set start)
                this.fБухгалтер = value;
                // *** Start programmer edit section *** (Накладная.Бухгалтер Set end)

                // *** End programmer edit section *** (Накладная.Бухгалтер Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной CustomAttributes)

        // *** End programmer edit section *** (Накладная.ЗаписьВНакладной CustomAttributes)
        public virtual IIS.Склад.DetailArrayOfЗаписьВНакладной ЗаписьВНакладной
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Get start)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Get start)
                if ((this.fЗаписьВНакладной == null))
                {
                    this.fЗаписьВНакладной = new IIS.Склад.DetailArrayOfЗаписьВНакладной(this);
                }
                IIS.Склад.DetailArrayOfЗаписьВНакладной result = this.fЗаписьВНакладной;
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Get end)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Set start)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Set start)
                this.fЗаписьВНакладной = value;
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Set end)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НакладнаяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяE", typeof(IIS.Склад.Накладная));
                }
            }
            
            /// <summary>
            /// "НакладнаяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяL", typeof(IIS.Склад.Накладная));
                }
            }
        }
    }
}
