//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поставки.
    /// </summary>
    // *** Start programmer edit section *** (Поставки CustomAttributes)

    // *** End programmer edit section *** (Поставки CustomAttributes)
    [BusinessServer("IIS.Склад.ПоставкиБС, Склад(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоставкиE", new string[] {
            "Количестсво as \'Количестсво\'",
            "Дата as \'Дата\'",
            "Склад as \'Склад\'",
            "Склад.Название as \'Название\'",
            "Товар as \'Товар\'",
            "Товар.Наименование as \'Наименование\'",
            "Машина.ВладелецМашины",
            "Машина.ВладелецМашины.Фамилия",
            "Машина as \'Машина\'",
            "Машина.Марка as \'Марка\'"}, Hidden=new string[] {
            "Склад.Название",
            "Товар.Наименование",
            "Машина.ВладелецМашины",
            "Машина.ВладелецМашины.Фамилия",
            "Машина.Марка"})]
    [MasterViewDefineAttribute("ПоставкиE", "Склад", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ПоставкиE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПоставкиE", "Машина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Марка")]
    [View("ПоставкиL", new string[] {
            "Количестсво as \'Количестсво\'",
            "Дата as \'Дата\'",
            "Склад.Название as \'Название\'",
            "Товар.Наименование as \'Наименование\'",
            "Машина.Марка as \'Марка\'",
            "Склад"}, Hidden=new string[] {
            "Склад"})]
    public class Поставки : ICSSoft.STORMNET.DataObject
    {
        
        private double fКоличестсво;
        
        private System.DateTime fДата;
        
        private IIS.Склад.Склад fСклад;
        
        private IIS.Склад.Товар fТовар;
        
        private IIS.Склад.Машина fМашина;
        
        // *** Start programmer edit section *** (Поставки CustomMembers)

        // *** End programmer edit section *** (Поставки CustomMembers)

        
        /// <summary>
        /// Количестсво.
        /// </summary>
        // *** Start programmer edit section *** (Поставки.Количестсво CustomAttributes)

        // *** End programmer edit section *** (Поставки.Количестсво CustomAttributes)
        public virtual double Количестсво
        {
            get
            {
                // *** Start programmer edit section *** (Поставки.Количестсво Get start)

                // *** End programmer edit section *** (Поставки.Количестсво Get start)
                double result = this.fКоличестсво;
                // *** Start programmer edit section *** (Поставки.Количестсво Get end)

                // *** End programmer edit section *** (Поставки.Количестсво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставки.Количестсво Set start)

                // *** End programmer edit section *** (Поставки.Количестсво Set start)
                this.fКоличестсво = value;
                // *** Start programmer edit section *** (Поставки.Количестсво Set end)

                // *** End programmer edit section *** (Поставки.Количестсво Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Поставки.Дата CustomAttributes)

        // *** End programmer edit section *** (Поставки.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Поставки.Дата Get start)

                // *** End programmer edit section *** (Поставки.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Поставки.Дата Get end)

                // *** End programmer edit section *** (Поставки.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставки.Дата Set start)

                // *** End programmer edit section *** (Поставки.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Поставки.Дата Set end)

                // *** End programmer edit section *** (Поставки.Дата Set end)
            }
        }
        
        /// <summary>
        /// Поставки.
        /// </summary>
        // *** Start programmer edit section *** (Поставки.Склад CustomAttributes)

        // *** End programmer edit section *** (Поставки.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual IIS.Склад.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Поставки.Склад Get start)

                // *** End programmer edit section *** (Поставки.Склад Get start)
                IIS.Склад.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Поставки.Склад Get end)

                // *** End programmer edit section *** (Поставки.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставки.Склад Set start)

                // *** End programmer edit section *** (Поставки.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Поставки.Склад Set end)

                // *** End programmer edit section *** (Поставки.Склад Set end)
            }
        }
        
        /// <summary>
        /// Поставки.
        /// </summary>
        // *** Start programmer edit section *** (Поставки.Товар CustomAttributes)

        // *** End programmer edit section *** (Поставки.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Склад.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Поставки.Товар Get start)

                // *** End programmer edit section *** (Поставки.Товар Get start)
                IIS.Склад.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Поставки.Товар Get end)

                // *** End programmer edit section *** (Поставки.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставки.Товар Set start)

                // *** End programmer edit section *** (Поставки.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Поставки.Товар Set end)

                // *** End programmer edit section *** (Поставки.Товар Set end)
            }
        }
        
        /// <summary>
        /// Поставки.
        /// </summary>
        // *** Start programmer edit section *** (Поставки.Машина CustomAttributes)

        // *** End programmer edit section *** (Поставки.Машина CustomAttributes)
        [PropertyStorage(new string[] {
                "Машина"})]
        [NotNull()]
        public virtual IIS.Склад.Машина Машина
        {
            get
            {
                // *** Start programmer edit section *** (Поставки.Машина Get start)

                // *** End programmer edit section *** (Поставки.Машина Get start)
                IIS.Склад.Машина result = this.fМашина;
                // *** Start programmer edit section *** (Поставки.Машина Get end)

                // *** End programmer edit section *** (Поставки.Машина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставки.Машина Set start)

                // *** End programmer edit section *** (Поставки.Машина Set start)
                this.fМашина = value;
                // *** Start programmer edit section *** (Поставки.Машина Set end)

                // *** End programmer edit section *** (Поставки.Машина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставкиE", typeof(IIS.Склад.Поставки));
                }
            }
            
            /// <summary>
            /// "ПоставкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставкиL", typeof(IIS.Склад.Поставки));
                }
            }
        }
    }
}
