//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Электронный_Магазин
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Склад.
    /// </summary>
    // *** Start programmer edit section *** (Склад CustomAttributes)

    // *** End programmer edit section *** (Склад CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СкладE", new string[] {
            "Количество as \'Количество\'",
            "Стоимость as \'Стоимость\'",
            "Товар",
            "Товар.Наименование"}, Hidden=new string[] {
            "Товар.Наименование"})]
    [MasterViewDefineAttribute("СкладE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("СкладL", new string[] {
            "Количество as \'Количество\'",
            "Стоимость as \'Стоимость\'",
            "Товар.Наименование as \'Наименование Товара\'"})]
    public class Склад : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fСтоимость;
        
        private IIS.Электронный_Магазин.Товар fТовар;
        
        // *** Start programmer edit section *** (Склад CustomMembers)

        // *** End programmer edit section *** (Склад CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Количество CustomAttributes)

        // *** End programmer edit section *** (Склад.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Количество Get start)

                // *** End programmer edit section *** (Склад.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Склад.Количество Get end)

                // *** End programmer edit section *** (Склад.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Количество Set start)

                // *** End programmer edit section *** (Склад.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Склад.Количество Set end)

                // *** End programmer edit section *** (Склад.Количество Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Склад.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Стоимость Get start)

                // *** End programmer edit section *** (Склад.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (Склад.Стоимость Get end)

                // *** End programmer edit section *** (Склад.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Стоимость Set start)

                // *** End programmer edit section *** (Склад.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Склад.Стоимость Set end)

                // *** End programmer edit section *** (Склад.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Склад.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Товар CustomAttributes)

        // *** End programmer edit section *** (Склад.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Электронный_Магазин.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Товар Get start)

                // *** End programmer edit section *** (Склад.Товар Get start)
                IIS.Электронный_Магазин.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Склад.Товар Get end)

                // *** End programmer edit section *** (Склад.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Товар Set start)

                // *** End programmer edit section *** (Склад.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Склад.Товар Set end)

                // *** End programmer edit section *** (Склад.Товар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СкладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладE", typeof(IIS.Электронный_Магазин.Склад));
                }
            }
            
            /// <summary>
            /// "СкладL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладL", typeof(IIS.Электронный_Магазин.Склад));
                }
            }
        }
    }
}
