/*flexberryautogenerated="true"*/
namespace IIS.Книги
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class КнигаL : BaseListForm<Книга>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public КнигаL() : base(Книга.Views.КнигаL)
        {
            EditPage = КнигаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Kniga/KnigaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
