/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.Collections.Generic;

namespace IIS.Книги
{
    public partial class Query2 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void btFind_Click(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var books = ds.Query<Книга>(Книга.Views.КнигаL);
            int max = 0;
            List<int> counts = new List<int>();
           
            foreach (var item in books)
            {
                var count = ds.Query<АвторКнига>(АвторКнига.Views.АвторКнигаE).Where(a => a.Книга == item).Count();
                if (count > max)
                {
                    max = count;
                    blBooks.Items.Clear();
                    blBooks.Items.Add(item.Название);
                }
                else if (count == max)
                    blBooks.Items.Add(item.Название);
                //counts.Add(count);
            }
            lbCount.Text = lbCount.Text + max.ToString();
           
            

            
        }
    }
}
