/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.Collections.Generic;

namespace IIS.Книги
{
    public partial class Query3 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var pubs = ds.Query<Издательство>(Издательство.Views.ИздательствоL);
            blAuthors.Items.Clear();
            if (dlPublisher.Items.Count == 0)
                foreach (var item in pubs)
                {
                    dlPublisher.Items.Add(item.Название);
                }
        }

        protected void btFind_Click(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var books = ds.Query<Книга>(Книга.Views.КнигаL).Where(b => b.Издательство.Название == dlPublisher.SelectedValue);
            List<string> authors = new List<string>();
            foreach (var item in books)
            {
                var authbook = ds.Query<АвторКнига>(АвторКнига.Views.АвторКнигаE).Where(a => a.Книга == item);
                foreach (var subitem in authbook)
                {
                    ds.LoadObject(subitem);
                    ds.LoadObject(subitem.Автор);
                    authors.Add(subitem.Автор.Фамилия.ToString() + " " + subitem.Автор.Имя);                   
                }
            }
            IEnumerable<string> dict = authors.Distinct();
            foreach (var item in dict)
            {
                blAuthors.Items.Add(item);
            }
            //lbAuthors.Items.AddRange(dict);



        }
    }
}
