/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.Collections.Generic;

namespace IIS.Книги
{
    public partial class Query4 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            blAuthors.Items.Clear();
        }

        protected void btFind_Click(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var authors = ds.Query<Автор>(Автор.Views.АвторE);
            int max = 0;
            foreach (var item in authors)
            {
                
                var authbooks = item.АвторКнига.Cast<АвторКнига>().ToList();
                int sum = 0;
                foreach(var subitem in authbooks)
                {
                    ds.LoadObject(subitem.Книга);
                    sum += subitem.Книга.КоличествоСтраниц;
                }
                if (sum > max)
                {
                    max = sum;
                    blAuthors.Items.Clear();
                    blAuthors.Items.Add(item.Фамилия + " " + item.Имя);
                }
                else if (sum == max)
                    blAuthors.Items.Add(item.Фамилия + " " + item.Имя);
                
            }
            lbSum.Text = lbSum.Text + max.ToString();
        }
    }
}
