<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Query4.aspx.cs" Inherits="IIS.Книги.Query4" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="Label1" runat="server" Text="Здесь вы можете посмотреть авторов, опубликовавших наибольшее количество страниц"></asp:Label>
    <br />
    <asp:Button ID="btFind" runat="server" OnClick="btFind_Click" Text="Найти" />
    <br />
    <asp:Label ID="Label2" runat="server" Text="Результаты поиска"></asp:Label>
    <asp:BulletedList ID="blAuthors" runat="server">
    </asp:BulletedList>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
