/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.Collections.Generic;

namespace IIS.Книги
{
    public partial class Query4 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            blAuthors.Items.Clear();
        }

        protected void btFind_Click(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var authors = ds.Query<Автор>(Автор.Views.АвторE);
            
            foreach (var item in authors)
            {
                //var detail = new DetailArrayOfАвторКнига(item);
                //ds.LoadObjects(detail);
                //var authbook = ds.Query<АвторКнига>(АвторКнига.Views.АвторКнигаE).Where(ab => ab.Автор == item);
                
                var sum = item.АвторКнига.GetAllObjects();
               
                foreach(var subitem in sum)
                {
                    //subitem.AddLoadedProperties("Книга(КоличествоСтраниц)");
                    //subitem.Книга;
                    //ds.LoadObject(subitem);
                        
                   
                    
                    //ds.LoadObject(subitem.Книга);
                }
                
                //foreach (var subitem in authbook)
                //{
                //    //ds.LoadObject(subitem.Книга);

                //}
            }
        }
    }
}
