/*flexberryautogenerated="true"*/
namespace NewPlatform.Горводоканал
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ТипОбращенияL : BaseListForm<ТипОбращения>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ТипОбращенияL() : base(ТипОбращения.Views.ТипОбращенияL)
        {
            EditPage = ТипОбращенияE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/TipObrashheniya/TipObrashheniyaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
