//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Individual_work_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Владелец.
    /// </summary>
    // *** Start programmer edit section *** (Владелец CustomAttributes)

    // *** End programmer edit section *** (Владелец CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВладелецE", new string[] {
            "ФИО as \'ФИО\'"})]
    [View("ВладелецL", new string[] {
            "ФИО as \'ФИО\'"})]
    public class Владелец : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Владелец CustomMembers)

        // *** End programmer edit section *** (Владелец CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Владелец.ФИО CustomAttributes)

        // *** End programmer edit section *** (Владелец.ФИО CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Владелец.ФИО Get start)

                // *** End programmer edit section *** (Владелец.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Владелец.ФИО Get end)

                // *** End programmer edit section *** (Владелец.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Владелец.ФИО Set start)

                // *** End programmer edit section *** (Владелец.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Владелец.ФИО Set end)

                // *** End programmer edit section *** (Владелец.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВладелецE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВладелецE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВладелецE", typeof(IIS.Individual_work_1.Владелец));
                }
            }
            
            /// <summary>
            /// "ВладелецL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВладелецL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВладелецL", typeof(IIS.Individual_work_1.Владелец));
                }
            }
        }
    }
}
