//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Individual_work_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Информация о поступлении.
    /// </summary>
    // *** Start programmer edit section *** (ИнформацияОПоступлении CustomAttributes)

    // *** End programmer edit section *** (ИнформацияОПоступлении CustomAttributes)
    [AutoAltered()]
    [Caption("Информация о поступлении")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИнформацияОПоступленииE", new string[0])]
    [AssociatedDetailViewAttribute("ИнформацияОПоступленииE", "ТоварНаСкладе", "ТоварНаСкладеE", true, "", "Товар на складе", true, new string[] {
            ""})]
    [View("ИнформацияОПоступленииL", new string[0])]
    public class ИнформацияОПоступлении : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Individual_work_1.DetailArrayOfТоварНаСкладе fТоварНаСкладе;
        
        // *** Start programmer edit section *** (ИнформацияОПоступлении CustomMembers)

        // *** End programmer edit section *** (ИнформацияОПоступлении CustomMembers)

        
        /// <summary>
        /// Информация о поступлении.
        /// </summary>
        // *** Start programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе CustomAttributes)

        // *** End programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе CustomAttributes)
        public virtual IIS.Individual_work_1.DetailArrayOfТоварНаСкладе ТоварНаСкладе
        {
            get
            {
                // *** Start programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Get start)

                // *** End programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Get start)
                if ((this.fТоварНаСкладе == null))
                {
                    this.fТоварНаСкладе = new IIS.Individual_work_1.DetailArrayOfТоварНаСкладе(this);
                }
                IIS.Individual_work_1.DetailArrayOfТоварНаСкладе result = this.fТоварНаСкладе;
                // *** Start programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Get end)

                // *** End programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Set start)

                // *** End programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Set start)
                this.fТоварНаСкладе = value;
                // *** Start programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Set end)

                // *** End programmer edit section *** (ИнформацияОПоступлении.ТоварНаСкладе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИнформацияОПоступленииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнформацияОПоступленииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнформацияОПоступленииE", typeof(IIS.Individual_work_1.ИнформацияОПоступлении));
                }
            }
            
            /// <summary>
            /// "ИнформацияОПоступленииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнформацияОПоступленииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнформацияОПоступленииL", typeof(IIS.Individual_work_1.ИнформацияОПоступлении));
                }
            }
        }
    }
}
