//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Individual_work_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Артикул as \'Артикул\'",
            "Название as \'Название\'"})]
    [View("ТоварL", new string[] {
            "Артикул as \'Артикул\'",
            "Название as \'Название\'"})]
    public class Товар : IIS.Individual_work_1.НазваниеСкладаИТовара
    {
        
        private int fАртикул;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// Артикул.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Артикул CustomAttributes)

        // *** End programmer edit section *** (Товар.Артикул CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Артикул
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Артикул Get start)

                // *** End programmer edit section *** (Товар.Артикул Get start)
                int result = this.fАртикул;
                // *** Start programmer edit section *** (Товар.Артикул Get end)

                // *** End programmer edit section *** (Товар.Артикул Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Артикул Set start)

                // *** End programmer edit section *** (Товар.Артикул Set start)
                this.fАртикул = value;
                // *** Start programmer edit section *** (Товар.Артикул Set end)

                // *** End programmer edit section *** (Товар.Артикул Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Individual_work_1.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Individual_work_1.Товар));
                }
            }
        }
    }
}
