//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Individual_work_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар на складе.
    /// </summary>
    // *** Start programmer edit section *** (ТоварНаСкладе CustomAttributes)

    // *** End programmer edit section *** (ТоварНаСкладе CustomAttributes)
    [AutoAltered()]
    [Caption("Товар на складе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварНаСкладеE", new string[] {
            "Товар as \'Товар\'",
            "Количество as \'Количество (в тоннах)\'",
            "Склад as \'Склад\'",
            "Автомашина as \'Автомашина\'"})]
    [MasterViewDefineAttribute("ТоварНаСкладеE", "Автомашина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Марка")]
    public class ТоварНаСкладе : ICSSoft.STORMNET.DataObject
    {
        
        private double fКоличество;
        
        private IIS.Individual_work_1.Автомашина fАвтомашина;
        
        private IIS.Individual_work_1.Товар fТовар;
        
        private IIS.Individual_work_1.Склад fСклад;
        
        private IIS.Individual_work_1.ИнформацияОПоступлении fИнформацияОПоступлении;
        
        // *** Start programmer edit section *** (ТоварНаСкладе CustomMembers)

        // *** End programmer edit section *** (ТоварНаСкладе CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.Количество CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.Количество CustomAttributes)
        [NotNull()]
        public virtual double Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Get start)
                double result = this.fКоличество;
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Set end)
            }
        }
        
        /// <summary>
        /// Товар на складе.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.Автомашина CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.Автомашина CustomAttributes)
        [NotNull()]
        public virtual IIS.Individual_work_1.Автомашина Автомашина
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Автомашина Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.Автомашина Get start)
                IIS.Individual_work_1.Автомашина result = this.fАвтомашина;
                // *** Start programmer edit section *** (ТоварНаСкладе.Автомашина Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.Автомашина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Автомашина Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.Автомашина Set start)
                this.fАвтомашина = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.Автомашина Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.Автомашина Set end)
            }
        }
        
        /// <summary>
        /// Товар на складе.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.Товар CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.Товар CustomAttributes)
        [NotNull()]
        public virtual IIS.Individual_work_1.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Get start)
                IIS.Individual_work_1.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Set end)
            }
        }
        
        /// <summary>
        /// Товар на складе.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.Склад CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.Склад CustomAttributes)
        [NotNull()]
        public virtual IIS.Individual_work_1.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Get start)
                IIS.Individual_work_1.Склад result = this.fСклад;
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Individual_work_1.ИнформацияОПоступлении.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Individual_work_1.ИнформацияОПоступлении ИнформацияОПоступлении
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Get start)
                IIS.Individual_work_1.ИнформацияОПоступлении result = this.fИнформацияОПоступлении;
                // *** Start programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Set start)
                this.fИнформацияОПоступлении = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.ИнформацияОПоступлении Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварНаСкладеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварНаСкладеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварНаСкладеE", typeof(IIS.Individual_work_1.ТоварНаСкладе));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТоварНаСкладе.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТоварНаСкладе CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТоварНаСкладе CustomAttributes)
    public class DetailArrayOfТоварНаСкладе : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Individual_work_1.DetailArrayOfТоварНаСкладе members)

        // *** End programmer edit section *** (IIS.Individual_work_1.DetailArrayOfТоварНаСкладе members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТоварНаСкладе by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТоварНаСкладе.
        /// </summary>
        public DetailArrayOfТоварНаСкладе(IIS.Individual_work_1.ИнформацияОПоступлении fИнформацияОПоступлении) : 
                base(typeof(ТоварНаСкладе), ((ICSSoft.STORMNET.DataObject)(fИнформацияОПоступлении)))
        {
        }
        
        public IIS.Individual_work_1.ТоварНаСкладе this[int index]
        {
            get
            {
                return ((IIS.Individual_work_1.ТоварНаСкладе)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Individual_work_1.ТоварНаСкладе dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
