//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Lectures
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Предмет в семестре.
    /// </summary>
    // *** Start programmer edit section *** (ПредметВСеместре CustomAttributes)

    // *** End programmer edit section *** (ПредметВСеместре CustomAttributes)
    [AutoAltered()]
    [Caption("Предмет в семестре")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПредметВСеместреE", new string[] {
            "Предмет as \'Предмет\'",
            "КоличествоЧасовИзучения as \'Количество часов изучения\'",
            "Предмет.Название as \'Название\'"}, Hidden=new string[] {
            "Предмет.Название"})]
    [MasterViewDefineAttribute("ПредметВСеместреE", "Предмет", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class ПредметВСеместре : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличествоЧасовИзучения;
        
        private IIS.Lectures.Предмет fПредмет;
        
        private IIS.Lectures.Семестр fСеместр;
        
        // *** Start programmer edit section *** (ПредметВСеместре CustomMembers)

        // *** End programmer edit section *** (ПредметВСеместре CustomMembers)

        
        /// <summary>
        /// КоличествоЧасовИзучения.
        /// </summary>
        // *** Start programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения CustomAttributes)

        // *** End programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения CustomAttributes)
        public virtual int КоличествоЧасовИзучения
        {
            get
            {
                // *** Start programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Get start)

                // *** End programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Get start)
                int result = this.fКоличествоЧасовИзучения;
                // *** Start programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Get end)

                // *** End programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Set start)

                // *** End programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Set start)
                this.fКоличествоЧасовИзучения = value;
                // *** Start programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Set end)

                // *** End programmer edit section *** (ПредметВСеместре.КоличествоЧасовИзучения Set end)
            }
        }
        
        /// <summary>
        /// Предмет в семестре.
        /// </summary>
        // *** Start programmer edit section *** (ПредметВСеместре.Предмет CustomAttributes)

        // *** End programmer edit section *** (ПредметВСеместре.Предмет CustomAttributes)
        [PropertyStorage(new string[] {
                "Предмет"})]
        [NotNull()]
        public virtual IIS.Lectures.Предмет Предмет
        {
            get
            {
                // *** Start programmer edit section *** (ПредметВСеместре.Предмет Get start)

                // *** End programmer edit section *** (ПредметВСеместре.Предмет Get start)
                IIS.Lectures.Предмет result = this.fПредмет;
                // *** Start programmer edit section *** (ПредметВСеместре.Предмет Get end)

                // *** End programmer edit section *** (ПредметВСеместре.Предмет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредметВСеместре.Предмет Set start)

                // *** End programmer edit section *** (ПредметВСеместре.Предмет Set start)
                this.fПредмет = value;
                // *** Start programmer edit section *** (ПредметВСеместре.Предмет Set end)

                // *** End programmer edit section *** (ПредметВСеместре.Предмет Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Lectures.Семестр.
        /// </summary>
        // *** Start programmer edit section *** (ПредметВСеместре.Семестр CustomAttributes)

        // *** End programmer edit section *** (ПредметВСеместре.Семестр CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Семестр"})]
        public virtual IIS.Lectures.Семестр Семестр
        {
            get
            {
                // *** Start programmer edit section *** (ПредметВСеместре.Семестр Get start)

                // *** End programmer edit section *** (ПредметВСеместре.Семестр Get start)
                IIS.Lectures.Семестр result = this.fСеместр;
                // *** Start programmer edit section *** (ПредметВСеместре.Семестр Get end)

                // *** End programmer edit section *** (ПредметВСеместре.Семестр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредметВСеместре.Семестр Set start)

                // *** End programmer edit section *** (ПредметВСеместре.Семестр Set start)
                this.fСеместр = value;
                // *** Start programmer edit section *** (ПредметВСеместре.Семестр Set end)

                // *** End programmer edit section *** (ПредметВСеместре.Семестр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПредметВСеместреE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредметВСеместреE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредметВСеместреE", typeof(IIS.Lectures.ПредметВСеместре));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПредметВСеместре.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПредметВСеместре CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПредметВСеместре CustomAttributes)
    public class DetailArrayOfПредметВСеместре : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Lectures.DetailArrayOfПредметВСеместре members)

        // *** End programmer edit section *** (IIS.Lectures.DetailArrayOfПредметВСеместре members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПредметВСеместре by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПредметВСеместре.
        /// </summary>
        public DetailArrayOfПредметВСеместре(IIS.Lectures.Семестр fСеместр) : 
                base(typeof(ПредметВСеместре), ((ICSSoft.STORMNET.DataObject)(fСеместр)))
        {
        }
        
        public IIS.Lectures.ПредметВСеместре this[int index]
        {
            get
            {
                return ((IIS.Lectures.ПредметВСеместре)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Lectures.ПредметВСеместре dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
