//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.indiv_Firm
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Department.
    /// </summary>
    // *** Start programmer edit section *** (Department CustomAttributes)

    // *** End programmer edit section *** (Department CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("DepartmentE", new string[] {
            "name as \'Name\'",
            "Employee as \'Employee\'",
            "Employee.name as \'Name\'"}, Hidden=new string[] {
            "Employee.name"})]
    [AssociatedDetailViewAttribute("DepartmentE", "EmployeeInDepartment", "EmployeeInDepartmentE", true, "", "Employee in department", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("DepartmentE", "Employee", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "name")]
    [View("DepartmentL", new string[] {
            "name as \'Name\'",
            "Employee.name as \'Name\'"})]
    public class Department : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private IIS.indiv_Firm.Employee fEmployee;
        
        private IIS.indiv_Firm.DetailArrayOfEmployeeInDepartment fEmployeeInDepartment;
        
        // *** Start programmer edit section *** (Department CustomMembers)

        // *** End programmer edit section *** (Department CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (Department.name CustomAttributes)

        // *** End programmer edit section *** (Department.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (Department.name Get start)

                // *** End programmer edit section *** (Department.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (Department.name Get end)

                // *** End programmer edit section *** (Department.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Department.name Set start)

                // *** End programmer edit section *** (Department.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (Department.name Set end)

                // *** End programmer edit section *** (Department.name Set end)
            }
        }
        
        /// <summary>
        /// Department.
        /// </summary>
        // *** Start programmer edit section *** (Department.Employee CustomAttributes)

        // *** End programmer edit section *** (Department.Employee CustomAttributes)
        [PropertyStorage(new string[] {
                "Employee"})]
        [NotNull()]
        public virtual IIS.indiv_Firm.Employee Employee
        {
            get
            {
                // *** Start programmer edit section *** (Department.Employee Get start)

                // *** End programmer edit section *** (Department.Employee Get start)
                IIS.indiv_Firm.Employee result = this.fEmployee;
                // *** Start programmer edit section *** (Department.Employee Get end)

                // *** End programmer edit section *** (Department.Employee Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Department.Employee Set start)

                // *** End programmer edit section *** (Department.Employee Set start)
                this.fEmployee = value;
                // *** Start programmer edit section *** (Department.Employee Set end)

                // *** End programmer edit section *** (Department.Employee Set end)
            }
        }
        
        /// <summary>
        /// Department.
        /// </summary>
        // *** Start programmer edit section *** (Department.EmployeeInDepartment CustomAttributes)

        // *** End programmer edit section *** (Department.EmployeeInDepartment CustomAttributes)
        public virtual IIS.indiv_Firm.DetailArrayOfEmployeeInDepartment EmployeeInDepartment
        {
            get
            {
                // *** Start programmer edit section *** (Department.EmployeeInDepartment Get start)

                // *** End programmer edit section *** (Department.EmployeeInDepartment Get start)
                if ((this.fEmployeeInDepartment == null))
                {
                    this.fEmployeeInDepartment = new IIS.indiv_Firm.DetailArrayOfEmployeeInDepartment(this);
                }
                IIS.indiv_Firm.DetailArrayOfEmployeeInDepartment result = this.fEmployeeInDepartment;
                // *** Start programmer edit section *** (Department.EmployeeInDepartment Get end)

                // *** End programmer edit section *** (Department.EmployeeInDepartment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Department.EmployeeInDepartment Set start)

                // *** End programmer edit section *** (Department.EmployeeInDepartment Set start)
                this.fEmployeeInDepartment = value;
                // *** Start programmer edit section *** (Department.EmployeeInDepartment Set end)

                // *** End programmer edit section *** (Department.EmployeeInDepartment Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "DepartmentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DepartmentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DepartmentE", typeof(IIS.indiv_Firm.Department));
                }
            }
            
            /// <summary>
            /// "DepartmentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DepartmentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DepartmentL", typeof(IIS.indiv_Firm.Department));
                }
            }
        }
    }
}
