/*flexberryautogenerated="true"*/
namespace IIS.Авиакомпания
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class СотрудникиL : BaseListForm<Сотрудники>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public СотрудникиL() : base(Сотрудники.Views.СотрудникиL)
        {
            EditPage = СотрудникиE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Sotrudniki/SotrudnikiL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
