<%--flexberryautogenerated="true"--%>

<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Dvigateli.aspx.cs" Inherits="IIS.Авиакомпания.Двигатели" Title="Untitled Page" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
Запрос
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Количество двигателей у самолета указанной модели</h2>

    <div>
        Компания : <ac:AlphaNumericTextBox runat ="server" Type="Alpha" ID="num1" />
        Код : <ac:AlphaNumericTextBox runat ="server" Type="Numeric" ID="Num2" />
        <asp:Button runat="server" Text="Выполнить" ID="Button" OnClick="Button_Click"/>

    </div>
    <div>
        <ac:WebObjectListView runat="server" ID="Mom" />
    </div>
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
