/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;

namespace IIS.Авиакомпания
{
    public partial class Двигатели : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Mom.DataObjectTypes = new[] { typeof(ТипСамолета) };
            Mom.View = ТипСамолета.Views.Dvigateli;
            Mom.Operations.New = false;
            Mom.Operations.Edit = false;
            Mom.Operations.EditInRow = false;
            Mom.Operations.Delete = false;
            Mom.Operations.DeleteInRow = false;

        
            if (Session["nomer"] != null && Session["s"] != null)
            {    var ds = DataServiceProvider.DataService;
                var nomer = Session["nomer"].ToString();
                var s = Session["s"].ToString();
                var n = ds.Query<ТипСамолета>(ТипСамолета.Views.Dvigateli.Name).Where(g => g.Код== nomer).Where(c => c.Название == s);
                Mom.LimitFunction = LinqToLcs.GetLcs(n.Expression, ТипСамолета.Views.Dvigateli).LimitFunction;
            }
            else
            {
                Mom.LimitFunction = SQLWhereLanguageDef.LanguageDef.GetFunction(SQLWhereLanguageDef.LanguageDef.funcSQL, "1!=1");
            }
        }

        protected void Button_Click(object sender, EventArgs e)
        {
            var ds = DataServiceProvider.DataService;
            try {
                
                var nomer = Num2;
                var s = num1;
                Session["nomer"] = nomer.StringValue;
                Session["s"] = s.StringValue;
            }
            catch (Exception)
            {
                Session["nomer"] = null;
                Session["s"] = null;
            }
            Response.Redirect(Request.Url.ToString());
        }
    }
}
