<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Vozrast.aspx.cs" Inherits="IIS.Авиакомпания.Возраст" Title="Untitled Page" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
Запрос
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Количество двигателей у самолета указанной модели</h2>

    <div>
       Тип самолета: Боинг 746
       
        <%--<asp:Button runat="server" Text="Выполнить" ID="Button" OnClick="Button_Click"/>--%>

    </div>
    <div>
      Средний возраст   : <asp:Label runat ="server" ID="Num2" Font-Size="X-Large" />
    </div>
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
