//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Indiv_Bahtin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Человек.
    /// </summary>
    // *** Start programmer edit section *** (Человек CustomAttributes)

    // *** End programmer edit section *** (Человек CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧеловекE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'"})]
    [View("ЧеловекL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'"})]
    public class Человек : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        // *** Start programmer edit section *** (Человек CustomMembers)

        // *** End programmer edit section *** (Человек CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Человек.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Человек.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Человек.Фамилия Get start)

                // *** End programmer edit section *** (Человек.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Человек.Фамилия Get end)

                // *** End programmer edit section *** (Человек.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Человек.Фамилия Set start)

                // *** End programmer edit section *** (Человек.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Человек.Фамилия Set end)

                // *** End programmer edit section *** (Человек.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Человек.Имя CustomAttributes)

        // *** End programmer edit section *** (Человек.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Человек.Имя Get start)

                // *** End programmer edit section *** (Человек.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Человек.Имя Get end)

                // *** End programmer edit section *** (Человек.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Человек.Имя Set start)

                // *** End programmer edit section *** (Человек.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Человек.Имя Set end)

                // *** End programmer edit section *** (Человек.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Человек.Отчество CustomAttributes)

        // *** End programmer edit section *** (Человек.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Человек.Отчество Get start)

                // *** End programmer edit section *** (Человек.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Человек.Отчество Get end)

                // *** End programmer edit section *** (Человек.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Человек.Отчество Set start)

                // *** End programmer edit section *** (Человек.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Человек.Отчество Set end)

                // *** End programmer edit section *** (Человек.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧеловекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧеловекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧеловекE", typeof(IIS.Indiv_Bahtin.Человек));
                }
            }
            
            /// <summary>
            /// "ЧеловекL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧеловекL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧеловекL", typeof(IIS.Indiv_Bahtin.Человек));
                }
            }
        }
    }
}
