/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using ICSSoft.STORMNET.FunctionalLanguage;
using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
using ICSSoft.STORMNET.Web.AjaxControls.Forms;

namespace IIS.Lectures
{
    public partial class Запрос1 : BasePage
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;

            if (!IsPostBack)
            {
                var subjects = ds.Query<Предмет>(Предмет.Views.ПредметL.Name);
                foreach (var subject in subjects)
                    dropDownList1.Items.Add(subject.Название);
            }
        }

        protected void button1_Click(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;

            var notebooks = ds.Query<Тетрадь>(Тетрадь.Views.ТетрадьE.Name).Where(
                    t => t.ПредметВТетради.Cast<ПредметВТетради>().Any(
                        p => p.Предмет.Название == dropDownList1.SelectedValue)).OrderBy(p => p.Название).ToList();

            TableRow tr;
            TableCell tc;
            int i = 0;

            foreach (var notebook in notebooks)
            {
                i++;
                tr = new TableRow();

                tc = new TableCell();
                tc.Controls.Add(new LiteralControl(i + "."));
                tr.Cells.Add(tc);

                tc = new TableCell();
                tc.Controls.Add(new LiteralControl(notebook.Название));
                tr.Cells.Add(tc);

                tc = new TableCell();
                tc.Controls.Add(new LiteralControl(notebook.ЦветОбложки));
                tr.Cells.Add(tc);

                table1.Rows.Add(tr);
            }
        }
    }
}
