//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_40936
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Юридический as \'Юридический\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчеcтво as \'Отчеcтво\'",
            "АдресФизический as \'Адрес физический\'",
            "АдресЮридический as \'Адрес юридический\'"})]
    [View("КлиентL", new string[] {
            "Юридический as \'Юридический\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчеcтво as \'Отчеcтво\'",
            "АдресФизический as \'Адрес физический\'",
            "АдресЮридический as \'Адрес юридический\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private bool fЮридический;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчеcтво;
        
        private string fАдресФизический;
        
        private string fАдресЮридический;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// Юридический.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Юридический CustomAttributes)

        // *** End programmer edit section *** (Клиент.Юридический CustomAttributes)
        public virtual bool Юридический
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Юридический Get start)

                // *** End programmer edit section *** (Клиент.Юридический Get start)
                bool result = this.fЮридический;
                // *** Start programmer edit section *** (Клиент.Юридический Get end)

                // *** End programmer edit section *** (Клиент.Юридический Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Юридический Set start)

                // *** End programmer edit section *** (Клиент.Юридический Set start)
                this.fЮридический = value;
                // *** Start programmer edit section *** (Клиент.Юридический Set end)

                // *** End programmer edit section *** (Клиент.Юридический Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Клиент.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Get start)

                // *** End programmer edit section *** (Клиент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Клиент.Фамилия Get end)

                // *** End programmer edit section *** (Клиент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Set start)

                // *** End programmer edit section *** (Клиент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Клиент.Фамилия Set end)

                // *** End programmer edit section *** (Клиент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Имя CustomAttributes)

        // *** End programmer edit section *** (Клиент.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Имя Get start)

                // *** End programmer edit section *** (Клиент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Клиент.Имя Get end)

                // *** End programmer edit section *** (Клиент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Имя Set start)

                // *** End programmer edit section *** (Клиент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Клиент.Имя Set end)

                // *** End programmer edit section *** (Клиент.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчеcтво.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Отчеcтво CustomAttributes)

        // *** End programmer edit section *** (Клиент.Отчеcтво CustomAttributes)
        [StrLen(255)]
        public virtual string Отчеcтво
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Отчеcтво Get start)

                // *** End programmer edit section *** (Клиент.Отчеcтво Get start)
                string result = this.fОтчеcтво;
                // *** Start programmer edit section *** (Клиент.Отчеcтво Get end)

                // *** End programmer edit section *** (Клиент.Отчеcтво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Отчеcтво Set start)

                // *** End programmer edit section *** (Клиент.Отчеcтво Set start)
                this.fОтчеcтво = value;
                // *** Start programmer edit section *** (Клиент.Отчеcтво Set end)

                // *** End programmer edit section *** (Клиент.Отчеcтво Set end)
            }
        }
        
        /// <summary>
        /// АдресФизический.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.АдресФизический CustomAttributes)

        // *** End programmer edit section *** (Клиент.АдресФизический CustomAttributes)
        [StrLen(255)]
        public virtual string АдресФизический
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.АдресФизический Get start)

                // *** End programmer edit section *** (Клиент.АдресФизический Get start)
                string result = this.fАдресФизический;
                // *** Start programmer edit section *** (Клиент.АдресФизический Get end)

                // *** End programmer edit section *** (Клиент.АдресФизический Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.АдресФизический Set start)

                // *** End programmer edit section *** (Клиент.АдресФизический Set start)
                this.fАдресФизический = value;
                // *** Start programmer edit section *** (Клиент.АдресФизический Set end)

                // *** End programmer edit section *** (Клиент.АдресФизический Set end)
            }
        }
        
        /// <summary>
        /// АдресЮридический.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.АдресЮридический CustomAttributes)

        // *** End programmer edit section *** (Клиент.АдресЮридический CustomAttributes)
        [StrLen(255)]
        public virtual string АдресЮридический
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.АдресЮридический Get start)

                // *** End programmer edit section *** (Клиент.АдресЮридический Get start)
                string result = this.fАдресЮридический;
                // *** Start programmer edit section *** (Клиент.АдресЮридический Get end)

                // *** End programmer edit section *** (Клиент.АдресЮридический Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.АдресЮридический Set start)

                // *** End programmer edit section *** (Клиент.АдресЮридический Set start)
                this.fАдресЮридический = value;
                // *** Start programmer edit section *** (Клиент.АдресЮридический Set end)

                // *** End programmer edit section *** (Клиент.АдресЮридический Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.Product_40936.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.Product_40936.Клиент));
                }
            }
        }
    }
}
