//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_40936
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кредит.
    /// </summary>
    // *** Start programmer edit section *** (Кредит CustomAttributes)

    // *** End programmer edit section *** (Кредит CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КредитE", new string[] {
            "НомерСчёта as \'Номер счёта\'",
            "ДатаОткрытия as \'Дата открытия\'",
            "Дата as \'Дата\'",
            "Приход as \'Приход\'",
            "Расход as \'Расход\'",
            "Остаток as \'Остаток\'",
            "Заёмщик as \'Заёмщик\'",
            "Заёмщик.Фамилия as \'Фамилия\'"})]
    [View("КредитL", new string[] {
            "НомерСчёта as \'Номер счёта\'",
            "ДатаОткрытия as \'Дата открытия\'",
            "Дата as \'Дата\'",
            "Приход as \'Приход\'",
            "Расход as \'Расход\'",
            "Остаток as \'Остаток\'",
            "Заёмщик.Фамилия as \'Фамилия\'"})]
    public class Кредит : IIS.Product_40936.Счета
    {
        
        private IIS.Product_40936.Клиент fЗаёмщик;
        
        // *** Start programmer edit section *** (Кредит CustomMembers)

        // *** End programmer edit section *** (Кредит CustomMembers)

        
        /// <summary>
        /// Кредит.
        /// </summary>
        // *** Start programmer edit section *** (Кредит.Заёмщик CustomAttributes)

        // *** End programmer edit section *** (Кредит.Заёмщик CustomAttributes)
        [NotNull()]
        public virtual IIS.Product_40936.Клиент Заёмщик
        {
            get
            {
                // *** Start programmer edit section *** (Кредит.Заёмщик Get start)

                // *** End programmer edit section *** (Кредит.Заёмщик Get start)
                IIS.Product_40936.Клиент result = this.fЗаёмщик;
                // *** Start programmer edit section *** (Кредит.Заёмщик Get end)

                // *** End programmer edit section *** (Кредит.Заёмщик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кредит.Заёмщик Set start)

                // *** End programmer edit section *** (Кредит.Заёмщик Set start)
                this.fЗаёмщик = value;
                // *** Start programmer edit section *** (Кредит.Заёмщик Set end)

                // *** End programmer edit section *** (Кредит.Заёмщик Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КредитE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КредитE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КредитE", typeof(IIS.Product_40936.Кредит));
                }
            }
            
            /// <summary>
            /// "КредитL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КредитL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КредитL", typeof(IIS.Product_40936.Кредит));
                }
            }
        }
    }
}
