//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_40936
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сберегательные.
    /// </summary>
    // *** Start programmer edit section *** (Сберегательные CustomAttributes)

    // *** End programmer edit section *** (Сберегательные CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СберегательныеE", new string[] {
            "НомерСчёта as \'Номер счёта\'",
            "ДатаОткрытия as \'Дата открытия\'",
            "Дата as \'Дата\'",
            "Приход as \'Приход\'",
            "Расход as \'Расход\'",
            "Остаток as \'Остаток\'",
            "Владелец as \'Владелец\'",
            "Владелец.Фамилия as \'Фамилия\'"})]
    [View("СберегательныеL", new string[] {
            "НомерСчёта as \'Номер счёта\'",
            "ДатаОткрытия as \'Дата открытия\'",
            "Дата as \'Дата\'",
            "Приход as \'Приход\'",
            "Расход as \'Расход\'",
            "Остаток as \'Остаток\'",
            "Владелец.Фамилия as \'Фамилия\'"})]
    public class Сберегательные : IIS.Product_40936.Счета
    {
        
        private IIS.Product_40936.Клиент fВладелец;
        
        // *** Start programmer edit section *** (Сберегательные CustomMembers)

        // *** End programmer edit section *** (Сберегательные CustomMembers)

        
        /// <summary>
        /// Сберегательные.
        /// </summary>
        // *** Start programmer edit section *** (Сберегательные.Владелец CustomAttributes)

        // *** End programmer edit section *** (Сберегательные.Владелец CustomAttributes)
        [NotNull()]
        public virtual IIS.Product_40936.Клиент Владелец
        {
            get
            {
                // *** Start programmer edit section *** (Сберегательные.Владелец Get start)

                // *** End programmer edit section *** (Сберегательные.Владелец Get start)
                IIS.Product_40936.Клиент result = this.fВладелец;
                // *** Start programmer edit section *** (Сберегательные.Владелец Get end)

                // *** End programmer edit section *** (Сберегательные.Владелец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сберегательные.Владелец Set start)

                // *** End programmer edit section *** (Сберегательные.Владелец Set start)
                this.fВладелец = value;
                // *** Start programmer edit section *** (Сберегательные.Владелец Set end)

                // *** End programmer edit section *** (Сберегательные.Владелец Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СберегательныеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СберегательныеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СберегательныеE", typeof(IIS.Product_40936.Сберегательные));
                }
            }
            
            /// <summary>
            /// "СберегательныеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СберегательныеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СберегательныеL", typeof(IIS.Product_40936.Сберегательные));
                }
            }
        }
    }
}
