//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_40936
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Счета.
    /// </summary>
    // *** Start programmer edit section *** (Счета CustomAttributes)

    // *** End programmer edit section *** (Счета CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СчетаE", new string[] {
            "НомерСчёта as \'Номер счёта\'",
            "ДатаОткрытия as \'Дата открытия\'",
            "Дата as \'Дата\'",
            "Приход as \'Приход\'",
            "Расход as \'Расход\'",
            "Остаток as \'Остаток\'"})]
    [View("СчетаL", new string[] {
            "НомерСчёта as \'Номер счёта\'",
            "ДатаОткрытия as \'Дата открытия\'",
            "Дата as \'Дата\'",
            "Приход as \'Приход\'",
            "Расход as \'Расход\'",
            "Остаток as \'Остаток\'"})]
    public class Счета : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерСчёта;
        
        private System.DateTime fДатаОткрытия = System.DateTime.Now;
        
        private System.DateTime fДата;
        
        private double fПриход;
        
        private double fРасход;
        
        private double fОстаток;
        
        // *** Start programmer edit section *** (Счета CustomMembers)

        // *** End programmer edit section *** (Счета CustomMembers)

        
        /// <summary>
        /// НомерСчёта.
        /// </summary>
        // *** Start programmer edit section *** (Счета.НомерСчёта CustomAttributes)

        // *** End programmer edit section *** (Счета.НомерСчёта CustomAttributes)
        public virtual int НомерСчёта
        {
            get
            {
                // *** Start programmer edit section *** (Счета.НомерСчёта Get start)

                // *** End programmer edit section *** (Счета.НомерСчёта Get start)
                int result = this.fНомерСчёта;
                // *** Start programmer edit section *** (Счета.НомерСчёта Get end)

                // *** End programmer edit section *** (Счета.НомерСчёта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Счета.НомерСчёта Set start)

                // *** End programmer edit section *** (Счета.НомерСчёта Set start)
                this.fНомерСчёта = value;
                // *** Start programmer edit section *** (Счета.НомерСчёта Set end)

                // *** End programmer edit section *** (Счета.НомерСчёта Set end)
            }
        }
        
        /// <summary>
        /// ДатаОткрытия.
        /// </summary>
        // *** Start programmer edit section *** (Счета.ДатаОткрытия CustomAttributes)

        // *** End programmer edit section *** (Счета.ДатаОткрытия CustomAttributes)
        public virtual System.DateTime ДатаОткрытия
        {
            get
            {
                // *** Start programmer edit section *** (Счета.ДатаОткрытия Get start)

                // *** End programmer edit section *** (Счета.ДатаОткрытия Get start)
                System.DateTime result = this.fДатаОткрытия;
                // *** Start programmer edit section *** (Счета.ДатаОткрытия Get end)

                // *** End programmer edit section *** (Счета.ДатаОткрытия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Счета.ДатаОткрытия Set start)

                // *** End programmer edit section *** (Счета.ДатаОткрытия Set start)
                this.fДатаОткрытия = value;
                // *** Start programmer edit section *** (Счета.ДатаОткрытия Set end)

                // *** End programmer edit section *** (Счета.ДатаОткрытия Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Счета.Дата CustomAttributes)

        // *** End programmer edit section *** (Счета.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Счета.Дата Get start)

                // *** End programmer edit section *** (Счета.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Счета.Дата Get end)

                // *** End programmer edit section *** (Счета.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Счета.Дата Set start)

                // *** End programmer edit section *** (Счета.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Счета.Дата Set end)

                // *** End programmer edit section *** (Счета.Дата Set end)
            }
        }
        
        /// <summary>
        /// Приход.
        /// </summary>
        // *** Start programmer edit section *** (Счета.Приход CustomAttributes)

        // *** End programmer edit section *** (Счета.Приход CustomAttributes)
        public virtual double Приход
        {
            get
            {
                // *** Start programmer edit section *** (Счета.Приход Get start)

                // *** End programmer edit section *** (Счета.Приход Get start)
                double result = this.fПриход;
                // *** Start programmer edit section *** (Счета.Приход Get end)

                // *** End programmer edit section *** (Счета.Приход Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Счета.Приход Set start)

                // *** End programmer edit section *** (Счета.Приход Set start)
                this.fПриход = value;
                // *** Start programmer edit section *** (Счета.Приход Set end)

                // *** End programmer edit section *** (Счета.Приход Set end)
            }
        }
        
        /// <summary>
        /// Расход.
        /// </summary>
        // *** Start programmer edit section *** (Счета.Расход CustomAttributes)

        // *** End programmer edit section *** (Счета.Расход CustomAttributes)
        public virtual double Расход
        {
            get
            {
                // *** Start programmer edit section *** (Счета.Расход Get start)

                // *** End programmer edit section *** (Счета.Расход Get start)
                double result = this.fРасход;
                // *** Start programmer edit section *** (Счета.Расход Get end)

                // *** End programmer edit section *** (Счета.Расход Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Счета.Расход Set start)

                // *** End programmer edit section *** (Счета.Расход Set start)
                this.fРасход = value;
                // *** Start programmer edit section *** (Счета.Расход Set end)

                // *** End programmer edit section *** (Счета.Расход Set end)
            }
        }
        
        /// <summary>
        /// Остаток.
        /// </summary>
        // *** Start programmer edit section *** (Счета.Остаток CustomAttributes)

        // *** End programmer edit section *** (Счета.Остаток CustomAttributes)
        public virtual double Остаток
        {
            get
            {
                // *** Start programmer edit section *** (Счета.Остаток Get start)

                // *** End programmer edit section *** (Счета.Остаток Get start)
                double result = this.fОстаток;
                // *** Start programmer edit section *** (Счета.Остаток Get end)

                // *** End programmer edit section *** (Счета.Остаток Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Счета.Остаток Set start)

                // *** End programmer edit section *** (Счета.Остаток Set start)
                this.fОстаток = value;
                // *** Start programmer edit section *** (Счета.Остаток Set end)

                // *** End programmer edit section *** (Счета.Остаток Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СчетаE", typeof(IIS.Product_40936.Счета));
                }
            }
            
            /// <summary>
            /// "СчетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СчетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СчетаL", typeof(IIS.Product_40936.Счета));
                }
            }
        }
    }
}
