/*flexberryautogenerated="true"*/

namespace IIS.Склад
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.Web.AjaxControls;
    using ICSSoft.STORMNET.Web.Tools;
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System.Linq;
    using ICSSoft.STORMNET.Windows.Forms;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.Web.Tools.WGEFeatures;

    public partial class СкладE : BaseEditForm<Склад>
    {
        /// <summary>
        /// Конструктор формы.
        /// </summary>
        public СкладE()
            : base(Склад.Views.СкладE)
        {
        }

        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Sklad/SkladE.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            //АГЕ ТоварНаСкладе сугубо для чтения, строки добавляются при добавлении поставок, руками в АГЕ ничего не добавляется
            ctrlТоварНаСкладе.Operations.Delete = false;
            ctrlТоварНаСкладе.Operations.Add = false;
            ctrlТоварНаСкладе.Operations.PlusInRow = false;
            ctrlТоварНаСкладе.Operations.DeleteInRow = false;
            ctrlТоварНаСкладе.Enabled = false;
            ctrlТоварНаСкладе.AddLookUpSettings(Information.ExtractPropertyPath<ТоварНаСкладе>(r => r.Товар), 
                new LookUpSetting { LookUpBtnVisible = false, LookUpClearBtnVisible = false });}

        /// <summary>
        /// Здесь лучше всего писать бизнес-логику, оперируя только объектом данных.
        /// </summary>
        protected override void PreApplyToControls()
        {

        }

        /// <summary>
        /// Здесь лучше всего изменять свойства контролов на странице,
        /// которые не обрабатываются WebBinder.
        /// </summary>
        protected override void PostApplyToControls()
        {

        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }

    }
}